/* Wortschatz für Wördle.

   LOESUNGEN  – Wörter, die gezogen werden können. Jedes trägt seinen Tipp:
                eine Umschreibung, in der das Wort selbst nicht vorkommt.
   WEITERE    – zusätzlich erlaubte Rateworte ohne Tipp. Sie tauchen nie
                als Lösung auf, dürfen aber eingegeben werden.

   Alle Wörter in Großbuchstaben, genau fünf Zeichen. Ä, Ö, Ü zählen als
   ein Zeichen und haben eine eigene Taste. ß kommt nicht vor.
*/

const LOESUNGEN = [
  ['ABEND', 'Tageszeit nach dem Sonnenuntergang, vor der Nacht.'],
  ['ADERN', 'Feine Röhren, in denen das Blut fließt. Auch im Blatt und im Marmor.'],
  ['ADLER', 'Großer Greifvogel mit weiter Spannweite, Wappentier vieler Länder.'],
  ['AMPEL', 'Steht an der Kreuzung und schaltet von Rot über Gelb auf Grün.'],
  ['AMSEL', 'Schwarzer Gartenvogel mit gelbem Schnabel, singt im Frühjahr früh vom Dach.'],
  ['ANGEL', 'Rute mit Schnur und Haken, holt Fische aus dem See. Auch das Gelenk der Tür.'],
  ['ANGST', 'Beklemmendes Gefühl vor Gefahr, treibt den Puls hoch.'],
  ['ANKER', 'Schweres Eisen an der Kette, hält das Schiff an Ort und Stelle.'],
  ['APFEL', 'Rundes Obst vom Baum, rot, grün oder gelb – steckt im Strudel und im Mus.'],
  ['BAUER', 'Bewirtschaftet Felder und Vieh. Im Schach die schwächste Figur.'],
  ['BEERE', 'Kleine weiche Frucht am Strauch, blau, rot oder schwarz.'],
  ['BEINE', 'Zwei davon tragen dich, unten sind die Füße dran.'],
  ['BERGE', 'Hohe Erhebungen mit Gipfeln, dorthin fährt man zum Skilaufen.'],
  ['BESEN', 'Borsten am Stiel, kehrt den Boden. Fahrzeug der Hexe.'],
  ['BIBER', 'Nagetier mit breitem Kellenschwanz, staut Bäche und fällt Bäume mit den Zähnen.'],
  ['BIENE', 'Summt von Blüte zu Blüte, sammelt Nektar und macht daraus Honig.'],
  ['BIRNE', 'Obst mit dickem Bauch und schmalem Hals. Hängt auch an der Zimmerdecke und leuchtet.'],
  ['BLITZ', 'Greller Zacken am Gewitterhimmel, der Donner folgt kurz darauf.'],
  ['BLUME', 'Wächst im Beet, hat Stiel und Blüte, kommt zum Geburtstag in die Vase.'],
  ['BLUSE', 'Leichtes Oberteil mit Knopfleiste, klassisch für Damen.'],
  ['BODEN', 'Worauf du stehst – oder der staubige Raum ganz oben unterm Dach.'],
  ['BOGEN', 'Krumme Linie. Damit schießt man Pfeile, in der Architektur trägt er das Gewölbe.'],
  ['BOHNE', 'Kern aus der grünen Schote – und das, was für Kaffee gemahlen wird.'],
  ['BRAUE', 'Der Haarbogen über dem Auge, den man beim Staunen hochzieht.'],
  ['BRAUN', 'Farbe von Erde, Schokolade und der Haut nach dem Urlaub.'],
  ['BRAUT', 'Am Hochzeitstag trägt sie Weiß und Schleier.'],
  ['BREIT', 'Von einer Seite zur anderen viel Maß – Gegenteil von schmal.'],
  ['BRIEF', 'Kommt mit Marke im Umschlag und wird in den Kasten geworfen.'],
  ['BRUST', 'Vorderseite des Oberkörpers, dahinter schlägt das Herz. Auch eine Schwimmart.'],
  ['BUCHE', 'Laubbaum mit glatter grauer Rinde, im Herbst kupferrot. Beliebtes Möbelholz.'],
  ['BÜHNE', 'Erhöhtes Podest im Theater, dort steht der Schauspieler im Scheinwerfer.'],
  ['CLOWN', 'Rote Nase, große Schuhe, bringt im Zirkus die Kinder zum Lachen.'],
  ['COUCH', 'Gepolstertes Möbel zum Sitzen und Langlegen vor dem Fernseher.'],
  ['CURRY', 'Gelbe Gewürzmischung aus Indien, würzt Reis, Huhn und Wurst.'],
  ['DACHS', 'Nachtaktives Waldtier mit schwarzweiß gestreiftem Kopf, gräbt weite Baue.'],
  ['DAMPF', 'Was aus dem Wasserkocher steigt. Trieb früher die Lokomotiven an.'],
  ['DATUM', 'Tag, Monat, Jahr – steht oben rechts auf jedem Formular.'],
  ['DECKE', 'Liegt beim Fernsehen über den Beinen. Und ist zugleich das Gegenteil vom Fußboden.'],
  ['DIELE', 'Erster Raum hinter der Wohnungstür, wo die Jacken hängen. Auch ein langes Holzbrett.'],
  ['DRAHT', 'Dünner, biegsamer Metallfaden. Man hat ihn auch zu jemandem, mit dem man gut kann.'],
  ['DRAMA', 'Theaterstück mit ernstem Stoff. Auch das große Theater um Kleinigkeiten.'],
  ['DRECK', 'Was am Schuh klebt, wenn man über den Acker gelaufen ist.'],
  ['DÜNEN', 'Vom Wind aufgeworfene Sandhügel am Strand, von Halmen bewachsen.'],
  ['EBENE', 'Flaches Land ohne Berge. In der Mathematik eine Fläche ohne Krümmung.'],
  ['ECKIG', 'Mit Kanten und Winkeln, gerade nicht rund.'],
  ['EIMER', 'Runder Behälter mit Henkel, für Wasser, Sand oder den Wischmopp.'],
  ['EISEN', 'Graues Metall, das rostet. Beim Golf auch ein Schläger.'],
  ['ENGEL', 'Himmlischer Bote mit Flügeln, sitzt an Weihnachten auf der Baumspitze.'],
  ['ENKEL', 'Das Kind deines Kindes – Oma und Opa freuen sich darauf.'],
  ['ERBSE', 'Kleine grüne Kugel aus der Schote. Eine davon lag unter der Matratze der Prinzessin.'],
  ['ERNTE', 'Was der Bauer im Spätsommer von den Feldern holt.'],
  ['ESSEN', 'Was dreimal am Tag auf den Tisch kommt – und die Tätigkeit dazu.'],
  ['ESSIG', 'Saure Würzflüssigkeit, kommt mit Öl an den Salat.'],
  ['FADEN', 'Dünner Zwirn auf der Rolle, gehört durchs Nadelöhr. Man verliert ihn beim Reden.'],
  ['FAHNE', 'Buntes Tuch an der Stange, wird bei der Siegerehrung gehisst.'],
  ['FÄHRE', 'Schiff, das Autos und Menschen ans andere Ufer bringt.'],
  ['FALKE', 'Schneller Greifvogel, stürzt sich aus großer Höhe auf die Beute.'],
  ['FARBE', 'Rot, Blau, Grün – und was im Eimer steckt, wenn die Wand gestrichen wird.'],
  ['FASAN', 'Bunter Hühnervogel im Feld, mit sehr langem Schwanz.'],
  ['FEDER', 'Trägt den Vogel. Steckt gespannt im Kugelschreiber und in der Matratze.'],
  ['FEIER', 'Anlass mit Gästen, Kuchen und Musik – Geburtstag, Hochzeit, Jubiläum.'],
  ['FEIGE', 'Süße Südfrucht voller Kernchen, oft getrocknet. Auch: ängstlich.'],
  ['FEILE', 'Raues Werkzeug, glättet Metall – die kleine davon die Fingernägel.'],
  ['FELGE', 'Metallrad, auf das der Reifen gezogen wird. Auch eine Übung am Reck.'],
  ['FERNE', 'Wo der Horizont ist. Dorthin schweift der Blick, wenn man träumt.'],
  ['FERSE', 'Hinterer Teil des Fußes, dort drückt der neue Schuh. Achilles war dort verwundbar.'],
  ['FEUER', 'Brennt, knistert und wärmt – aber die Wehr rückt aus, wenn es zu groß wird.'],
  ['FISCH', 'Lebt im Wasser, atmet durch Kiemen und hat Flossen und Schuppen.'],
  ['FLOSS', 'Zusammengebundene Baumstämme, treiben den Fluss hinab.'],
  ['FLÖTE', 'Blasinstrument mit Grifflöchern, in der Schule aus Kunststoff.'],
  ['FLOTT', 'Zügig und schwungvoll erledigt. Umgangssprachlich auch: sieht schick aus.'],
  ['FLUSS', 'Wasser, das zum Meer strömt. Rhein, Main, Donau.'],
  ['FRAGE', 'Endet mit einem Zeichen wie ein Haken und verlangt eine Antwort.'],
  ['FRIST', 'Zeitraum bis zu einem Stichtag – beim Finanzamt besser nicht verstreichen lassen.'],
  ['FROST', 'Wenn es unter null geht und das Wasser gefriert.'],
  ['FUCHS', 'Rotes Raubtier mit buschiger Rute, gilt im Märchen als besonders schlau.'],
  ['FUNKE', 'Winziger Glutspritzer vom Feuerstein. Auch der zündende Moment einer Idee.'],
  ['GABEL', 'Besteck mit Zinken, liegt links vom Teller. Auch die Stelle, wo sich der Weg teilt.'],
  ['GÄSTE', 'Wer eingeladen kommt und bewirtet wird.'],
  ['GEBET', 'Gesprochene Zwiesprache mit Gott, oft mit gefalteten Händen.'],
  ['GEIER', 'Kahlköpfiger Segler über der Steppe, frisst, was liegen bleibt.'],
  ['GEIGE', 'Streichinstrument, das unters Kinn geklemmt wird.'],
  ['GEIST', 'Weißes Gespenst im Schloss – und zugleich der Verstand eines Menschen.'],
  ['GLANZ', 'Was frisch poliertes Silber und ein sauberes Auto ausstrahlen.'],
  ['GLEIS', 'Zwei Schienen auf Schwellen, daran hält der Zug.'],
  ['GLÜCK', 'Wenn alles gut geht – und das Gefühl danach. Vierblättrig zu finden.'],
  ['GNADE', 'Milde statt Strafe – der Präsident kann sie einem Verurteilten gewähren.'],
  ['GRUND', 'Warum etwas geschieht. Und das Unterste eines Sees.'],
  ['GURKE', 'Langes grünes Gemüse, sauer eingelegt im Glas, gehört auf jedes Butterbrot.'],
  ['HAARE', 'Wachsen auf dem Kopf und werden beim Friseur geschnitten.'],
  ['HAFEN', 'Wo die Schiffe anlegen und die Container stehen. Hamburg hat einen großen.'],
  ['HAFER', 'Getreide für Flocken und Brei, mag auch das Pferd.'],
  ['HAGEL', 'Eiskörner, die im Sommergewitter prasseln und Autos verbeulen.'],
  ['HAKEN', 'Gebogenes Metallstück für die Jacke an der Wand. Auch der versteckte Nachteil einer Sache.'],
  ['HALLE', 'Sehr großer überdachter Raum – für Turniere, Messen oder Maschinen.'],
  ['HANDY', 'Kleiner Begleiter in der Hosentasche, mit dem man telefoniert und alles andere macht.'],
  ['HARFE', 'Großes Saiteninstrument zum Zupfen, steht schräg vor dem Spieler.'],
  ['HAUBE', 'Kopfbedeckung mit Bändern. Sitzt am Auto auch vorn über dem Motor.'],
  ['HAUCH', 'Kaum spürbarer Atemzug. Auch: nur ein winziges bisschen von etwas.'],
  ['HAUPT', 'Gehobenes Wort für den Kopf. Als Vorsilbe: das Wichtigste von allem.'],
  ['HEBEL', 'Stange, die Kraft vervielfacht. Archimedes wollte damit die Welt aus den Angeln heben.'],
  ['HECHT', 'Räuber im See mit langem Maul voller Zähne. Auch ein Sprung ins Wasser.'],
  ['HECKE', 'Dichte grüne Wand aus Sträuchern an der Grundstücksgrenze, wird geschnitten.'],
  ['HEIDE', 'Karge Landschaft mit lila Blüten, berühmt in der Lüneburger Gegend.'],
  ['HEISS', 'So warm, dass man sich die Finger verbrennt.'],
  ['HENNE', 'Weibliches Huhn, legt die Eier.'],
  ['HERDE', 'Große Gruppe weidender Tiere, vom Hirten zusammengehalten.'],
  ['HOBEL', 'Werkzeug des Schreiners, zieht Späne vom Brett.'],
  ['HÖHLE', 'Dunkler Hohlraum im Fels, mit Tropfsteinen. Auch die Wohnung des Bären.'],
  ['HONIG', 'Goldgelbe Süße aus dem Bienenstock, kommt aufs Brot.'],
  ['HOSEN', 'Kleidungsstücke mit zwei Beinen, kurz oder lang getragen.'],
  ['HÜFTE', 'Gelenk zwischen Rumpf und Bein, dort sitzt der Gürtel.'],
  ['HÜGEL', 'Sanfte kleine Erhebung im Gelände, noch kein richtiger Berg.'],
  ['HUMOR', 'Die Gabe, über die Dinge lachen zu können.'],
  ['HÜRDE', 'Hindernis auf der Laufbahn, wird übersprungen. Auch übertragen gemeint.'],
  ['HÜTTE', 'Einfaches Häuschen aus Holz, oben am Berg oder hinten im Garten.'],
  ['HYÄNE', 'Lachendes Raubtier der Savanne mit sehr kräftigem Gebiss.'],
  ['IDEEN', 'Einfälle im Kopf, manchmal kommt eine wie ein Blitz.'],
  ['IMKER', 'Wer Bienen hält und den Honig schleudert.'],
  ['INSEL', 'Land ringsum von Wasser umgeben. Sylt, Rügen, Mallorca.'],
  ['JACKE', 'Was man beim Rausgehen überzieht, mit Reißverschluss oder Knöpfen.'],
  ['JÄGER', 'Geht mit Hund und Gewehr in den Wald, sitzt auf dem Hochsitz.'],
  ['JAHRE', 'Zeiträume von je zwölf Monaten, sie vergehen wie im Flug.'],
  ['JEANS', 'Robuste blaue Hose aus festem Baumwollstoff, mit Nieten an den Taschen.'],
  ['JOKER', 'Karte, die jede andere ersetzen darf. Auch der Trumpf im Ärmel.'],
  ['JUBEL', 'Lauter Freudenschrei der Menge, wenn das Tor fällt.'],
  ['JUNGE', 'Männliches Kind.'],
  ['KABEL', 'Isolierter Strang, der Strom oder Daten leitet – hinterm Schreibtisch immer verknotet.'],
  ['KÄFIG', 'Gitterbehausung für Vogel oder Hamster.'],
  ['KAJAK', 'Schmales Boot mit Doppelpaddel, stammt aus dem hohen Norden.'],
  ['KAKAO', 'Braunes Pulver aus der Bohne, mit heißer Milch ein Kindergetränk.'],
  ['KAMEL', 'Wüstentier mit Höckern, kommt lange ohne Wasser aus.'],
  ['KAMIN', 'Offene Feuerstelle im Wohnzimmer, mit Rauchabzug durchs Dach.'],
  ['KANAL', 'Künstlich gegrabener Wasserweg. Auch ein Programmplatz im Fernsehen.'],
  ['KANNE', 'Gefäß mit Henkel und Ausguss, für Tee, Kaffee oder Gießwasser.'],
  ['KANTE', 'Scharfe Linie, wo zwei Flächen zusammenstoßen – am Tisch schmerzhaft fürs Schienbein.'],
  ['KARTE', 'Zeigt gefaltet den Weg, steckt im Portemonnaie oder wird beim Skat gemischt.'],
  ['KASSE', 'Wo im Laden bezahlt wird – und die Krankenversicherung heißt auch so.'],
  ['KATER', 'Männliche Katze. Und was am Morgen nach zu viel Wein im Kopf hämmert.'],
  ['KATZE', 'Schnurrt auf dem Sofa, fängt Mäuse, hat angeblich neun Leben.'],
  ['KEGEL', 'Spitz zulaufender Körper. Neun davon stehen am Ende der Bahn.'],
  ['KEHLE', 'Vorn am Hals – dort geht der Schluck hinunter und die Stimme heraus.'],
  ['KEKSE', 'Knuspriges Kleingebäck aus der Dose, vor Weihnachten in vielen Formen.'],
  ['KELCH', 'Trinkgefäß mit Fuß, beim Abendmahl in der Kirche.'],
  ['KELLE', 'Großer Löffel zum Schöpfen der Suppe. Der Maurer hat auch eine.'],
  ['KERZE', 'Wachs mit Docht, spendet Licht beim Stromausfall und im Advent.'],
  ['KETTE', 'Verbundene Glieder aus Metall – am Fahrrad oder um den Hals.'],
  ['KLANG', 'Wie etwas tönt – der volle Ton eines Instruments oder einer Stimme.'],
  ['KLAUE', 'Krallenbewehrter Fuß eines Raubtiers. Auch eine unleserliche Handschrift.'],
  ['KLEID', 'Einteiliges Stück Stoff zum Anziehen, oben und unten in einem, meist für Damen.'],
  ['KLIMA', 'Das Wetter über Jahrzehnte gemittelt – Thema jeder großen Konferenz.'],
  ['KNOPF', 'Kleine runde Scheibe, geht durchs Loch und hält das Hemd zu. Auch zum Drücken.'],
  ['KOALA', 'Grauer Kletterer aus Australien, frisst Eukalyptus und verschläft den Tag.'],
  ['KOHLE', 'Schwarzer Brennstoff aus der Grube. Salopp auch: Geld.'],
  ['KOMET', 'Himmelskörper mit leuchtendem Schweif, kommt alle paar Jahrzehnte vorbei.'],
  ['KOMMA', 'Kleines Häkchen, das den Satz gliedert. Sitzt auch zwischen den Ziffern.'],
  ['KÖNIG', 'Trägt Krone und sitzt auf dem Thron. Im Schach die wichtigste Figur.'],
  ['KRAFT', 'Was man zum Heben braucht. In der Physik gemessen in Newton.'],
  ['KRÄHE', 'Schwarzer kluger Vogel, sitzt gern auf dem Acker und ruft rau.'],
  ['KRANZ', 'Rund gebundenes Gesteck aus Zweigen – an der Tür oder mit vier Kerzen.'],
  ['KREBS', 'Tier mit Scheren am Meeresgrund. Auch ein Sternzeichen im Juli.'],
  ['KREIS', 'Runde Linie, überall gleich weit vom Mittelpunkt. Auch eine Verwaltungseinheit.'],
  ['KREUZ', 'Zwei Balken übereinander. Steht auf dem Kirchturm, und der Rücken heißt auch so.'],
  ['KRONE', 'Goldreif mit Zacken auf dem Königskopf. Sitzt auch auf dem geschliffenen Zahn.'],
  ['KÜCHE', 'Raum mit Herd, Spüle und Kühlschrank.'],
  ['KUGEL', 'Vollkommen runder Körper – beim Eis, beim Billard, beim Lotto.'],
  ['KÜKEN', 'Frisch geschlüpftes gelbes Federknäuel im Hühnerstall.'],
  ['KUNST', 'Was im Museum hängt und steht. Und was schwer zu machen ist.'],
  ['KURVE', 'Krümmung der Straße. Auch die Linie im Diagramm.'],
  ['KÜSTE', 'Streifen, wo das Land ans Meer stößt.'],
  ['LADEN', 'Geschäft mit Tresen und Ware. Auch das Brett vorm Fenster – und was der Akku braucht.'],
  ['LAMPE', 'Gibt Licht, steht auf dem Nachttisch oder hängt über dem Esstisch.'],
  ['LANZE', 'Lange Stichwaffe des Ritters beim Turnier.'],
  ['LARVE', 'Jugendform eines Insekts, noch ohne Flügel. Auch eine Maske im Fasching.'],
  ['LATTE', 'Schmales Brett am Zaun. Beim Fußball das Ding über dem Torwart.'],
  ['LAUNE', 'Gemütszustand – kann gut, schlecht oder wechselhaft sein.'],
  ['LEBEN', 'Was zwischen Geburt und Tod passiert.'],
  ['LEBER', 'Größtes inneres Organ, entgiftet den Körper und leidet unter Alkohol.'],
  ['LEDER', 'Gegerbte Tierhaut für Schuhe, Gürtel und Sofa.'],
  ['LEUTE', 'Mehrere Menschen, ganz allgemein.'],
  ['LICHT', 'Was die Sonne schickt und der Schalter anmacht.'],
  ['LIEBE', 'Das stärkste Gefühl zwischen zwei Menschen.'],
  ['LILIE', 'Große duftende Blüte mit sechs Blättern, oft weiß, häufig im Trauerstrauß.'],
  ['LINDE', 'Herzblättriger Baum, blüht im Sommer, steht traditionell auf dem Dorfplatz.'],
  ['LINIE', 'Gerade zwischen zwei Punkten. Auch der Weg von Bus oder Bahn.'],
  ['LINSE', 'Geschliffenes Glas in Brille und Kamera. Auch die kleine Hülsenfrucht im Eintopf.'],
  ['LIPPE', 'Weicher Rand des Mundes, wird zum Kuss gespitzt.'],
  ['LOCKE', 'Gedrehte Haarsträhne, die sich von selbst ringelt.'],
  ['LOGIK', 'Die Lehre vom folgerichtigen Denken: wenn A, dann B.'],
  ['LUCHS', 'Wildkatze mit Pinselohren, hat sprichwörtlich sehr scharfe Augen.'],
  ['LÜGEN', 'Unwahrheiten, von denen es heißt, sie hätten kurze Beine.'],
  ['LUNGE', 'Paariges Organ im Brustkorb, nimmt den Sauerstoff auf.'],
  ['LYRIK', 'Dichtung in Versen und Strophen, oft gereimt.'],
  ['MACHT', 'Wer sie hat, bestimmt über andere und gibt sie ungern ab.'],
  ['MAGEN', 'Hohlorgan unter dem Zwerchfell, in dem das Essen verdaut wird.'],
  ['MAGIE', 'Zauberei mit geheimen Kräften, Stab und spitzem Hut.'],
  ['MÄHNE', 'Langes Haar am Hals von Pferd und Löwe.'],
  ['MALER', 'Streicht die Wände – oder hängt im Museum.'],
  ['MANGO', 'Süße gelborange Tropenfrucht mit großem flachem Kern.'],
  ['MARKT', 'Platz mit Ständen, wo samstags Obst und Gemüse verkauft wird.'],
  ['MAUER', 'Wand aus Stein und Mörtel. Eine berühmte teilte Berlin.'],
  ['MÄUSE', 'Mehrere kleine graue Nager mit langem Schwanz.'],
  ['MEILE', 'Angelsächsisches Längenmaß, gut 1,6 Kilometer.'],
  ['MEISE', 'Kleiner Gartenvogel mit farbiger Kappe, hängt im Winter am Futterknödel.'],
  ['MESSE', 'Große Ausstellung für Fachbesucher. Und der Gottesdienst der Katholiken.'],
  ['METER', 'Grundeinheit der Länge, festgelegt über die Lichtgeschwindigkeit; ein Zollstock misst zwei davon.'],
  ['MIETE', 'Was man dem Eigentümer der Wohnung jeden Monat überweist.'],
  ['MILCH', 'Weißes Getränk von der Kuh, kommt in den Kaffee.'],
  ['MINZE', 'Kühlendes Kraut für Tee und Zahnpasta.'],
  ['MITTE', 'Der Punkt, der von allen Rändern gleich weit weg ist.'],
  ['MÖBEL', 'Tisch, Stuhl, Schrank – alles, was die Wohnung einrichtet.'],
  ['MÖHRE', 'Oranges Wurzelgemüse, das Kaninchen lieben.'],
  ['MOLCH', 'Lurch mit langem Schwanz, lebt im Teich und an Land.'],
  ['MONAT', 'Zwölf davon ergeben ein Jahr.'],
  ['MOTOR', 'Wandelt Kraftstoff oder Strom in Bewegung, brummt unter der Haube.'],
  ['MOTTE', 'Nachtfalter, der ums Licht flattert und Löcher in den Pullover frisst.'],
  ['MÜCKE', 'Sticht in lauen Sommernächten und summt vorher am Ohr.'],
  ['MÜHLE', 'Gebäude mit Flügeln oder Wasserrad, das Korn zu Mehl mahlt. Auch ein Brettspiel.'],
  ['MÜNZE', 'Rundes Geldstück aus Metall, klimpert im Portemonnaie.'],
  ['MUSIK', 'Töne in geordneter Folge, kommt aus dem Radio.'],
  ['MUTIG', 'Wer sich trotz Angst traut.'],
  ['MÜTZE', 'Weiche Kopfbedeckung gegen Kälte, oft mit Bommel.'],
  ['NABEL', 'Kleine Narbe mitten auf dem Bauch, Rest der Schnur von der Mutter.'],
  ['NACHT', 'Dunkle Zeit zwischen Abend und Morgen.'],
  ['NADEL', 'Spitz und dünn – zum Nähen, am Tannenbaum, oder auf dem Kompass.'],
  ['NAGEL', 'Wird mit dem Hammer in die Wand geschlagen. Sitzt auch vorn auf dem Finger.'],
  ['NARBE', 'Blasser Streifen auf der Haut, der nach einer Verletzung bleibt.'],
  ['NATUR', 'Wald, Wiese, Tiere – alles, was nicht vom Menschen gemacht ist.'],
  ['NEBEL', 'Wolke am Boden, im Herbst sieht man kaum die Hand vor Augen.'],
  ['NEFFE', 'Der Sohn deines Bruders oder deiner Schwester.'],
  ['NIERE', 'Bohnenförmiges Organ, das das Blut filtert. Man hat zwei davon.'],
  ['NOTEN', 'Zeichen auf fünf Linien, sagen dem Musiker den Ton. Gibt es auch im Zeugnis.'],
  ['NUDEL', 'Teigware aus Mehl und Ei, kommt in kochendes Salzwasser.'],
  ['NÜSSE', 'Harte Schalen mit fettem Kern, werden mit dem Knacker geöffnet.'],
  ['OASEN', 'Grüne Flecken mit Wasser und Palmen mitten in der Wüste.'],
  ['OCHSE', 'Kastriertes männliches Rind, zog früher den Pflug.'],
  ['OFFEN', 'Nicht verschlossen. Auch: ehrlich heraus sagen, was man denkt.'],
  ['OLIVE', 'Kleine grüne oder schwarze Frucht aus dem Süden, liefert Öl.'],
  ['ONKEL', 'Der Bruder von Mutter oder Vater.'],
  ['OPFER', 'Wer den Schaden abbekommen hat. Auch die Gabe an die Götter.'],
  ['ORGEL', 'Riesiges Instrument mit Pfeifen und Pedalen, steht auf der Empore der Kirche.'],
  ['OSTEN', 'Himmelsrichtung, in der die Sonne aufgeht.'],
  ['OTTER', 'Schwimmendes Marder-Tier mit dichtem Fell, knackt Muscheln auf dem Bauch.'],
  ['PAKET', 'Kommt vom Versandhändler, der Bote klingelt damit an der Tür.'],
  ['PALME', 'Baum mit Wedeln statt Ästen, steht am Strand und trägt Kokosnüsse.'],
  ['PANDA', 'Schwarzweißer Bär aus China, frisst fast nur Bambus.'],
  ['PAPST', 'Oberhaupt der katholischen Kirche, wohnt im Vatikan.'],
  ['PASTA', 'Italienische Teigware – Spaghetti, Penne, Farfalle.'],
  ['PAUSE', 'Kurze Unterbrechung – in der Schule mit Brot und Schulhof.'],
  ['PEDAL', 'Wird mit dem Fuß getreten, am Rad, am Klavier oder im Auto.'],
  ['PERLE', 'Schimmernde Kugel aus der Muschel, aufgereiht als Halskette.'],
  ['PFAHL', 'Dicker Holzstab, der in den Boden gerammt wird.'],
  ['PFEIL', 'Fliegt vom Bogen. Zeigt als Zeichen die Richtung an.'],
  ['PFERD', 'Reittier mit Hufen und Mähne, wiehert im Stall.'],
  ['PFLUG', 'Gerät, das die Ackerfurche zieht, hinter dem Traktor.'],
  ['PIANO', 'Tasteninstrument mit Hämmerchen und Saiten. Auf Italienisch auch: leise.'],
  ['PILOT', 'Sitzt im Cockpit und fliegt das Flugzeug.'],
  ['PILZE', 'Wachsen im Herbstwald mit Hut und Stiel, manche davon giftig.'],
  ['PISTE', 'Präparierte Abfahrt für Skifahrer. Auch die Startbahn am Flughafen.'],
  ['PIZZA', 'Runder Teigfladen mit Tomate und Käse, kommt aus Neapel.'],
  ['PLATZ', 'Freie Fläche mitten in der Stadt. Auch der Sitz im Zug – und ein Kommando an den Hund.'],
  ['POKAL', 'Silberner Becher, den der Sieger in die Höhe stemmt.'],
  ['PRIMA', 'Umgangssprachlich: richtig gut, bestens.'],
  ['PRINZ', 'Sohn des Königs, küsst im Märchen die Schlafende wach.'],
  ['PROBE', 'Versuch vor dem Ernstfall – beim Theater und beim Chor. Auch die Menge fürs Labor.'],
  ['PROSA', 'Text in gewöhnlichen Sätzen, ohne Reim und Versmaß.'],
  ['PUDEL', 'Hunderasse mit lockigem Fell, wird gern geschoren.'],
  ['PUNKT', 'Beendet den Satz. Auch die Zählung im Spiel und der Ort ohne Ausdehnung.'],
  ['PUPPE', 'Spielzeug in Menschengestalt. Auch das Zwischenstadium der Raupe.'],
  ['QUARK', 'Weißer Frischkäse, sauer und cremig, kommt in den Kuchen.'],
  ['QUOTE', 'Anteil in Prozent – beim Fernsehen die Zahl der Zuschauer.'],
  ['RADIO', 'Kasten, aus dem Musik und Nachrichten kommen, empfängt über Antenne.'],
  ['RASEN', 'Kurz gemähte Grasfläche im Garten oder im Stadion.'],
  ['RATTE', 'Großer grauer Nager in der Kanalisation.'],
  ['RAUCH', 'Graue Schwaden über dem Feuer, steigen aus dem Schornstein.'],
  ['RAUPE', 'Gefräßiges Larvenstadium, aus dem später ein Schmetterling wird.'],
  ['RECHT', 'Die Gesamtheit der Gesetze. Und das Gegenteil von falsch.'],
  ['REGAL', 'Möbel aus Brettern, auf denen die Bücher stehen.'],
  ['REGEN', 'Wasser, das aus den Wolken fällt – Schirm aufspannen.'],
  ['REIME', 'Gleichklang am Zeilenende, wie Herz und Schmerz.'],
  ['REISE', 'Fahrt an einen weit entfernten Ort, mit Koffer.'],
  ['RENTE', 'Monatliches Geld für Menschen, die nicht mehr arbeiten müssen.'],
  ['RIESE', 'Sehr großer Mensch im Märchen, gegen den David antrat.'],
  ['RINDE', 'Äußere Schicht des Baumstamms. Auch die harte Außenseite von Brot und Käse.'],
  ['RIPPE', 'Gebogener Knochen im Brustkorb. Zwölf Paare schützen die Organe.'],
  ['ROBBE', 'Rundlicher Meeressäuger, der sich an den Strand legt und bellt.'],
  ['ROMAN', 'Langes erzählendes Buch mit vielen Kapiteln.'],
  ['RUDER', 'Langes Blatt, mit dem man das Boot vorwärts zieht. Auch die Steuerung des Schiffs.'],
  ['RUINE', 'Verfallenes Gemäuer einer alten Burg.'],
  ['SAHNE', 'Fetter Teil der Milch, wird steif geschlagen und kommt auf den Kuchen.'],
  ['SAITE', 'Gespannter Draht auf Gitarre und Geige, erzeugt beim Zupfen den Ton.'],
  ['SALAT', 'Grüne Blätter in der Schüssel, mit Essig und Öl angemacht.'],
  ['SALBE', 'Fettige Creme aus der Tube, wird auf die wunde Haut gestrichen.'],
  ['SAMEN', 'Kleines Korn, aus dem eine neue Pflanze wächst.'],
  ['SAUER', 'Geschmack von Zitrone und Essig. Auch: verärgert.'],
  ['SÄULE', 'Runde tragende Stütze am griechischen Tempel.'],
  ['SCHAF', 'Wolliges Weidetier, das blökt und geschoren wird.'],
  ['SCHAL', 'Langes Tuch, das man sich im Winter um den Hals wickelt.'],
  ['SCHUH', 'Kommt an den Fuß, hat Sohle und Schnürsenkel.'],
  ['SEGEL', 'Großes Tuch am Mast, das den Wind fängt und das Boot treibt.'],
  ['SEHNE', 'Zäher Strang, der den Muskel am Knochen hält. Auch am Bogen gespannt.'],
  ['SEIFE', 'Schäumt beim Händewaschen und macht sauber.'],
  ['SEITE', 'Ein Blatt im Buch, von vorn betrachtet. Auch links oder rechts von etwas.'],
  ['SHIRT', 'Leichtes Oberteil mit kurzen Ärmeln, gern bedruckt.'],
  ['SILBE', 'Sprechteil eines Wortes – Ka-mel hat zwei davon.'],
  ['SIRUP', 'Dickflüssige Zuckerlösung, wird mit Wasser zu Limonade.'],
  ['SKIER', 'Zwei schmale Bretter, damit gleitet man die Piste hinab.'],
  ['SOCKE', 'Kommt zwischen Fuß und Schuh, verschwindet gern in der Waschmaschine.'],
  ['SOHLE', 'Unterseite des Fußes und des Schuhs.'],
  ['SONNE', 'Der Stern, um den die Erde kreist, macht Tag und Wärme.'],
  ['SORGE', 'Drückende Gedanken an etwas, das schiefgehen könnte.'],
  ['SOSSE', 'Flüssige Beigabe zum Braten, wird mit Mehl gebunden.'],
  ['SPALT', 'Schmaler Riss, eine nur einen Zentimeter weit geöffnete Tür.'],
  ['SPATZ', 'Frecher brauner Kleinvogel, pickt Krümel vom Tisch im Straßencafé.'],
  ['SPECK', 'Fettes Stück vom Schwein, brutzelt in der Pfanne. Sitzt auch auf den Hüften.'],
  ['SPIEL', 'Was hier gerade läuft – mit Regeln, Runden und einem Ziel.'],
  ['SPITZ', 'Vorn schmal zulaufend wie Nadel und Bleistift.'],
  ['SPORT', 'Körperliche Betätigung mit Schweiß, Verein und Wettkampf.'],
  ['STADT', 'Große Ansammlung von Häusern mit Rathaus und Straßenbahn.'],
  ['STAHL', 'Harte Legierung aus Eisen und Kohlenstoff, wird in der Hütte gekocht.'],
  ['STALL', 'Gebäude für Kühe, Pferde oder Hühner, riecht nach Stroh.'],
  ['STAUB', 'Feine graue Schicht auf dem Regal, wird gesaugt oder gewischt.'],
  ['STEAK', 'Kurz gebratenes Stück Fleisch, wahlweise blutig oder durch.'],
  ['STEIN', 'Harter Brocken aus dem Boden. Steckt auch in der Kirsche.'],
  ['STERN', 'Leuchtender Punkt am Nachthimmel. Auch die Auszeichnung des Restaurants.'],
  ['STIEL', 'Langer Griff an Besen und Pfanne. Auch der grüne Halm der Blume.'],
  ['STIFT', 'Womit man schreibt oder malt. Auch der Lehrling in der Werkstatt.'],
  ['STIRN', 'Glatte Fläche über den Augen, unter dem Haaransatz.'],
  ['STOFF', 'Gewebe für Kleidung. Und was für die Prüfung gelernt werden muss.'],
  ['STOLZ', 'Aufrechtes Gefühl über die eigene Leistung – im Übermaß eine Sünde.'],
  ['STROM', 'Kommt aus der Steckdose. Auch ein sehr großer Fluss.'],
  ['STUFE', 'Ein Tritt der Treppe. Auch ein Grad auf einer Skala.'],
  ['STUHL', 'Sitzmöbel mit vier Beinen und Lehne.'],
  ['STURM', 'Sehr starker Wind, der Bäume umwirft.'],
  ['STUTE', 'Weibliches Pferd, Mutter des Fohlens.'],
  ['SUMPF', 'Nasses weiches Gelände, in dem der Fuß versinkt.'],
  ['SUPPE', 'Warme Flüssigkeit im tiefen Teller, wird gelöffelt.'],
  ['SUSHI', 'Japanische Häppchen aus Reis, rohem Fisch und Algenblatt.'],
  ['TAFEL', 'Grüne Wand im Klassenzimmer mit Kreide. Auch die Schokolade.'],
  ['TANNE', 'Immergrüner Nadelbaum, steht an Weihnachten geschmückt im Wohnzimmer.'],
  ['TANTE', 'Die Schwester von Mutter oder Vater.'],
  ['TAPIR', 'Plumpes Urwaldtier mit kurzem Rüssel, verwandt mit Nashorn und Pferd.'],
  ['TASSE', 'Gefäß mit Henkel für Kaffee und Tee.'],
  ['TASTE', 'Wird gedrückt – am Klavier, am Telefon, unter dem Finger.'],
  ['TAUBE', 'Grauer Vogel auf dem Marktplatz, gilt als Zeichen des Friedens.'],
  ['TEICH', 'Kleines stehendes Gewässer mit Seerosen und Fröschen.'],
  ['THEMA', 'Worum es in einem Text oder Gespräch geht.'],
  ['THRON', 'Prunkvoller Sessel, auf dem der Herrscher sitzt.'],
  ['TIEFE', 'Wie weit es nach unten geht – beim See in Metern gemessen.'],
  ['TIGER', 'Große gestreifte Raubkatze aus Asien.'],
  ['TISCH', 'Platte auf Beinen, an der gegessen und gearbeitet wird.'],
  ['TITEL', 'Steht vorn auf dem Buch. Auch was der Meister gewinnt und der Doktor führt.'],
  ['TOAST', 'Weißbrotscheibe, im Gerät goldbraun geröstet. Auch ein Trinkspruch.'],
  ['TONNE', 'Tausend Kilogramm. Und der große Behälter für den Müll.'],
  ['TORTE', 'Mehrstöckiger Kuchen mit Creme, zum Geburtstag mit Kerzen.'],
  ['TRAUM', 'Bilder im Schlaf. Auch der große Wunsch fürs Leben.'],
  ['TREUE', 'Verlässlich zu jemandem stehen, über Jahre hinweg.'],
  ['TRUHE', 'Große Kiste mit Deckel zum Aufklappen – für Schätze oder Tiefkühlkost.'],
  ['TULPE', 'Frühlingsblume aus der Zwiebel, Wahrzeichen der Niederlande.'],
  ['TÜREN', 'Werden geöffnet, um in den Raum zu kommen, mit Klinke und Schloss.'],
  ['TÜRME', 'Mehrere hohe schmale Bauwerke, etwa an der Kirche oder im Schach.'],
  ['VATER', 'Männlicher Elternteil.'],
  ['VERSE', 'Zeilen eines Gedichts mit festem Rhythmus.'],
  ['VILLA', 'Großes vornehmes Wohnhaus mit Park drumherum.'],
  ['VOGEL', 'Tier mit Federn und Schnabel, das singt und fliegt.'],
  ['WAAGE', 'Zeigt das Gewicht an. Auch ein Sternzeichen im Oktober.'],
  ['WAFFE', 'Gerät zum Kämpfen – Schwert, Gewehr, Kanone.'],
  ['WAGEN', 'Fahrzeug auf Rädern. Und der Mut, etwas Riskantes zu tun.'],
  ['WALZE', 'Schwere Rolle, die den Asphalt platt drückt.'],
  ['WANNE', 'Großes Becken im Bad, in das man sich zum Baden legt.'],
  ['WANZE', 'Flaches Insekt mit Stechrüssel. Auch ein verstecktes Abhörgerät.'],
  ['WARZE', 'Kleine harte Wucherung auf der Haut, sitzt gern am Finger.'],
  ['WELLE', 'Rollt aufs Ufer zu. Auch das, worauf das Radio sendet.'],
  ['WELPE', 'Ganz junger Hund, tapsig und verspielt.'],
  ['WENDE', 'Kehrtmachen. Und der Umbruch von 1989 in Deutschland.'],
  ['WERFT', 'Betrieb am Wasser, in dem Schiffe gebaut und repariert werden.'],
  ['WESPE', 'Gelbschwarzes Insekt, das im Spätsommer über den Kuchen herfällt und sticht.'],
  ['WESTE', 'Ärmelloses Oberteil über dem Hemd. Sprichwörtlich sollte sie weiß sein.'],
  ['WIESE', 'Grüne Fläche mit Gras und Blumen, wird gemäht.'],
  ['WILLE', 'Innerer Entschluss, etwas durchzuziehen. Der letzte davon steht im Testament.'],
  ['WOCHE', 'Sieben Tage von Montag bis Sonntag.'],
  ['WOLKE', 'Weiße Ansammlung am Himmel, aus der es regnen kann.'],
  ['WOLLE', 'Weiches Garn vom Schaf, daraus wird der Pullover gestrickt.'],
  ['WUNDE', 'Verletzung der Haut, wird mit Pflaster versorgt.'],
  ['WURST', 'Fleisch in der Pelle – Brat-, Blut- oder Leber-. Und salopp: völlig egal.'],
  ['YACHT', 'Elegantes Freizeitschiff, mit Segel oder Motor.'],
  ['ZÄHNE', 'Weiße Beißer im Mund, morgens und abends geputzt.'],
  ['ZANGE', 'Werkzeug mit zwei Backen zum Greifen und Kneifen.'],
  ['ZÄUNE', 'Mehrere Begrenzungen aus Latten oder Draht rund ums Grundstück.'],
  ['ZEBRA', 'Gestreiftes Steppenpferd. Sein Name klebt auch am gestreiften Fußgängerübergang.'],
  ['ZEILE', 'Eine waagerechte Reihe Text auf dem Blatt.'],
  ['ZEUGE', 'Wer etwas gesehen hat und vor Gericht darüber aussagt.'],
  ['ZIEGE', 'Meckerndes Tier mit Hörnern und Bart, frisst alles.'],
  ['ZITAT', 'Wörtlich übernommener Satz, kommt in Anführungszeichen.'],
  ['ZUNGE', 'Bewegliches Muskelorgan im Mund, schmeckt und spricht.'],
  ['ZWERG', 'Kleiner Bergarbeiter im Märchen – sieben leben bei Schneewittchen.'],
];

/* Weitere gültige Rateworte – Wörter, die eingegeben werden dürfen, aber nie
   die Lösung sind und darum keinen Tipp brauchen.

   Von Hand zusammengestellt, damit an der App keine fremde Lizenz klebt:
   gängige Hauptwörter im Singular und Plural, gebeugte Zeitwörter, Eigenschafts-
   wörter und die häufigsten kleinen Wörter. Durchgehend groß geschrieben,
   ß steht als SS (GROSS, SPASS), Ä/Ö/Ü zählen als ein Zeichen. */
const WEITERE = [
  'ABART', 'ABBAU', 'ABGAS', 'ABTEI', 'ABTES', 'ABZUG', 'ACHSE', 'ACHTE', 'ACKER', 'ÄCKER',
  'ADELN', 'AFFEN', 'AGENT', 'AHNEN', 'AHNTE', 'AHORN', 'AKKUS', 'AKTEN', 'AKTIE', 'AKTIV',
  'AKUTE', 'ALARM', 'ALBEN', 'ALBUM', 'ALGEN', 'ALLEE', 'ALLER', 'ALLES', 'ALPEN', 'ALTAR',
  'ALTEN', 'ALTER', 'ALTES', 'ÄMTER', 'AMTES', 'ANBAU', 'ANGAB', 'ANKAM', 'ANLAG', 'ANRUF',
  'ANSAH', 'ANTIK', 'ANZUG', 'ÄPFEL', 'APRIL', 'ARENA', 'ARGEN', 'ÄRGER', 'ARMEE', 'ÄRMEL',
  'ARMEN', 'ARMES', 'AROMA', 'ÄRZTE', 'ASCHE', 'ASSEL', 'ÄSTEN', 'ASTES', 'ATEMS', 'ATLAS',
  'ATOME', 'AUGEN', 'AUGUR', 'AUTOR', 'AUTOS', 'BABYS', 'BÄCHE', 'BACKE', 'BÄCKT', 'BADEN',
  'BADET', 'BAHNE', 'BAHRE', 'BALGE', 'BALLE', 'BÄLLE', 'BANDE', 'BANGE', 'BANGT', 'BANJO',
  'BÄNKE', 'BANNE', 'BÄREN', 'BARON', 'BARTE', 'BÄRTE', 'BASIS', 'BATEN', 'BATIK', 'BAUCH',
  'BAUEN', 'BÄUME', 'BAUTE', 'BEBEN', 'BEBTE', 'BEETE', 'BEIDE', 'BEIGE', 'BEIZE', 'BEKAM',
  'BELAG', 'BELEG', 'BELLE', 'BELLT', 'BERGT', 'BERUF', 'BESTE', 'BETEN', 'BETET', 'BETON',
  'BETTE', 'BEUGT', 'BEULE', 'BEUTE', 'BEVOR', 'BEZUG', 'BIBEL', 'BIEGE', 'BIEGT', 'BIEST',
  'BIETE', 'BILDE', 'BINDE', 'BINSE', 'BIRKE', 'BISON', 'BISSE', 'BITTE', 'BIWAK', 'BLASE',
  'BLASS', 'BLATT', 'BLAUE', 'BLECH', 'BLEIB', 'BLICK', 'BLIEB', 'BLOCK', 'BLOND', 'BLUFF',
  'BLÜTE', 'BOCKE', 'BÖCKE', 'BÖGEN', 'BOHLE', 'BOHRT', 'BOMBE', 'BONUS', 'BOOTE', 'BÖRSE',
  'BÖSES', 'BOTEN', 'BOTES', 'BOTIN', 'BOXEN', 'BOXER', 'BRACH', 'BRAND', 'BRATE', 'BRAVE',
  'BRETT', 'BRISE', 'BROTE', 'BRUCH', 'BRÜHE', 'BUBEN', 'BUCHS', 'BUCHT', 'BUDEN', 'BÜGEL',
  'BUHLE', 'BUNDE', 'BÜNDE', 'BUNTE', 'BÜRDE', 'BÜRGE', 'BUSCH', 'BUSEN', 'BUSSE', 'CAFES',
  'CAMPS', 'CHAOS', 'CHEFS', 'CHILI', 'CHINA', 'CHIPS', 'CHÖRE', 'CHROM', 'CODES', 'CREME',
  'DAHER', 'DAMEN', 'DAMIT', 'DÄMME', 'DÄMON', 'DÄNEN', 'DANKE', 'DANKT', 'DARAN', 'DARIN',
  'DARUM', 'DATEI', 'DATEN', 'DAUER', 'DAVON', 'DECKT', 'DEGEN', 'DEHNE', 'DEHNT', 'DEICH',
  'DEINE', 'DEKAN', 'DELLE', 'DELTA', 'DEMUT', 'DENKE', 'DENKT', 'DEPOT', 'DICHT', 'DICKE',
  'DIEBE', 'DIEBS', 'DIENE', 'DIENT', 'DIESE', 'DINGE', 'DINGS', 'DIVAN', 'DOGGE', 'DOHLE',
  'DOLCH', 'DORFE', 'DOSEN', 'DOSIS', 'DRANG', 'DRAUF', 'DREHE', 'DREHT', 'DROGE', 'DROHT',
  'DRUCK', 'DUELL', 'DUETT', 'DUFTE', 'DÜFTE', 'DUMME', 'DUMPF', 'DÜNNE', 'DUNST', 'DURCH',
  'DURST', 'DUZEN', 'EBBEN', 'ECHSE', 'ECHTE', 'ECKEN', 'EDLER', 'EDLES', 'EFEUS', 'EGGEN',
  'EHREN', 'EHRTE', 'EICHE', 'EIDES', 'EIFER', 'EIGEN', 'EIGNE', 'EILEN', 'EILIG', 'EILTE',
  'EINEM', 'EINEN', 'EINER', 'EINES', 'EINIG', 'EINST', 'EISES', 'EISIG', 'EITEL', 'EITER',
  'EITLE', 'EKELN', 'EKELS', 'EKLAT', 'EKLIG', 'ELBEN', 'ELCHE', 'ELEND', 'ELFEN', 'ELFTE',
  'ELITE', 'EMAIL', 'ENDEN', 'ENDET', 'ENGEN', 'ENGES', 'ENTEN', 'ERBEN', 'ERDEN', 'ERGAB',
  'ERLEN', 'ERNST', 'ERSTE', 'ESELS', 'ETAGE', 'ETHIK', 'ETUIS', 'ETWAS', 'EULEN', 'EUREN',
  'EUROS', 'EUTER', 'EWIGE', 'EXAKT', 'EXTRA', 'FABEL', 'FÄDEN', 'FÄHIG', 'FAHRT', 'FÄHRT',
  'FAKIR', 'FALLE', 'FALLS', 'FÄLLT', 'FALTE', 'FANGE', 'FÄNGT', 'FASER', 'FASST', 'FAULE',
  'FAULT', 'FAUNA', 'FAUST', 'FAZIT', 'FEGEN', 'FEGTE', 'FEHLE', 'FEHLT', 'FEIND', 'FEINE',
  'FELDE', 'FELLE', 'FESTE', 'FETTE', 'FIBEL', 'FIGUR', 'FILET', 'FILME', 'FILZE', 'FINDE',
  'FINGE', 'FINTE', 'FIRMA', 'FIXER', 'FJORD', 'FLACH', 'FLAIR', 'FLECK', 'FLEHT', 'FLIEG',
  'FLIRT', 'FLORA', 'FLUCH', 'FLÜGE', 'FLUGS', 'FLUID', 'FOKUS', 'FOLGE', 'FOLGT', 'FOLIE',
  'FONDS', 'FORMT', 'FORST', 'FORUM', 'FOTOS', 'FRACK', 'FRAGT', 'FRASS', 'FRECH', 'FREIE',
  'FREMD', 'FREUT', 'FRIES', 'FROHE', 'FUGEN', 'FÜGEN', 'FÜHLE', 'FÜHLT', 'FÜHRT', 'FÜLLE',
  'FÜLLT', 'FUNDE', 'FUROR', 'FÜRST', 'FÜSSE', 'GABEN', 'GALLE', 'GAMBE', 'GÄNSE', 'GANZE',
  'GARBE', 'GARDE', 'GARNE', 'GASES', 'GASSE', 'GATTE', 'GEBEN', 'GEBOT', 'GEGEN', 'GEHEN',
  'GEHST', 'GEIZE', 'GEIZT', 'GELBE', 'GELDE', 'GELEE', 'GELTE', 'GEMÜT', 'GENAU', 'GENIE',
  'GENUG', 'GERÄT', 'GERNE', 'GERTE', 'GESTE', 'GIBST', 'GIFTE', 'GILDE', 'GIPSE', 'GLATT',
  'GLIED', 'GNOME', 'GOLDE', 'GOLEM', 'GÖNNE', 'GRABE', 'GRABT', 'GRÄBT', 'GRADE', 'GRAMM',
  'GRATE', 'GRAUE', 'GREIF', 'GREIS', 'GRIFF', 'GRILL', 'GRIMM', 'GROBE', 'GROLL', 'GROSS',
  'GRUBE', 'GRÜNE', 'GRUSS', 'GUAVE', 'GUCKT', 'GUMMI', 'GUNST', 'GURTE', 'GUTEN', 'GÜTER',
  'GUTES', 'HABEN', 'HADER', 'HAFTE', 'HAGER', 'HAHNE', 'HÄHNE', 'HALBE', 'HALLO', 'HALME',
  'HALTE', 'HÄLTS', 'HÄNDE', 'HÄNGE', 'HÄNGT', 'HARTE', 'HARZE', 'HASEN', 'HASST', 'HAUEN',
  'HAUER', 'HAUFE', 'HAUSE', 'HAUTE', 'HÄUTE', 'HEBEN', 'HEBER', 'HEFTE', 'HEILT', 'HEIZT',
  'HELFE', 'HELLE', 'HELME', 'HEMDE', 'HERBE', 'HERRN', 'HERZE', 'HEUER', 'HEUTE', 'HEXEN',
  'HEXER', 'HILFE', 'HILFT', 'HIRSE', 'HIRTE', 'HITZE', 'HOCKT', 'HÖFEN', 'HOFFT', 'HOHEN',
  'HOLDE', 'HOLEN', 'HOLST', 'HOLZE', 'HÖLZE', 'HORDE', 'HÖREN', 'HÖRST', 'HOTEL', 'HUFEN',
  'HUFES', 'HÜLLE', 'HUMUS', 'HUNDE', 'HUPEN', 'HÜPFT', 'HUSTE', 'HYMNE', 'IDIOM', 'IDIOT',
  'IGELN', 'IGELS', 'IGLUS', 'IHNEN', 'IKONE', 'IMMER', 'IMPFT', 'INDEX', 'INDIZ', 'INNEN',
  'INNIG', 'INTIM', 'IRREN', 'IRRER', 'IRRTE', 'JAGEN', 'JEDER', 'JENER', 'JETZT', 'JODEL',
  'JOLLE', 'JUCKT', 'JUNGS', 'JUNTA', 'JUWEL', 'KADER', 'KÄFER', 'KAHLE', 'KÄLTE', 'KAMPF',
  'KANON', 'KAPPE', 'KARGE', 'KARMA', 'KARRE', 'KARST', 'KASTE', 'KAUEN', 'KAUFE', 'KAUFT',
  'KEHRT', 'KEIME', 'KEIMT', 'KENNE', 'KENNT', 'KERBE', 'KERNE', 'KEULE', 'KIESE', 'KIOSK',
  'KIPPE', 'KIPPT', 'KISTE', 'KLAGE', 'KLAGT', 'KLAMM', 'KLARE', 'KLEBT', 'KLEIE', 'KLEIN',
  'KLIPP', 'KLOTZ', 'KLUFT', 'KLUGE', 'KNABE', 'KNAPP', 'KNAST', 'KNIEN', 'KNIET', 'KNIFF',
  'KNOTE', 'KOCHE', 'KÖCHE', 'KOCHT', 'KODEX', 'KOMIK', 'KOMMT', 'KONTO', 'KÖPFE', 'KOPIE',
  'KÖRBE', 'KORPS', 'KOSEN', 'KOSTE', 'KRACH', 'KRANK', 'KRAUS', 'KRAUT', 'KRIEG', 'KRIMI',
  'KRUME', 'KRUMM', 'KUBUS', 'KÜHLE', 'KÜHNE', 'KULTE', 'KUNDE', 'KUPPE', 'KURSE', 'KÜRZE',
  'KÜSSE', 'KÜSST', 'KUTTE', 'LABOR', 'LACHE', 'LACHS', 'LACHT', 'LACKE', 'LADET', 'LAGER',
  'LAICH', 'LAKAI', 'LAKEN', 'LANDE', 'LANGE', 'LÄNGE', 'LARGO', 'LASER', 'LASSE', 'LÄSST',
  'LASTE', 'LAUBE', 'LAUCH', 'LÄUFE', 'LÄUFT', 'LAUTE', 'LEDIG', 'LEERE', 'LEGAL', 'LEGEN',
  'LEGTE', 'LEHNE', 'LEHRE', 'LEHRT', 'LEIBE', 'LEIDE', 'LEIER', 'LEIHT', 'LEIME', 'LEINE',
  'LEISE', 'LEMUR', 'LENKT', 'LERNE', 'LERNT', 'LESEN', 'LIEBT', 'LIEFE', 'LIEGT', 'LIEST',
  'LIFTE', 'LIGEN', 'LIMES', 'LIMIT', 'LINKE', 'LINKS', 'LISTE', 'LITER', 'LOBEN', 'LOGIS',
  'LOHNE', 'LÖHNE', 'LOSEN', 'LÖSEN', 'LOSES', 'LOTSE', 'LOTUS', 'LÖWEN', 'LOYAL', 'LÜCKE',
  'LÜFTE', 'LUPEN', 'LURCH', 'LUXUS', 'MACHE', 'MÄDEL', 'MADEN', 'MAGER', 'MAHLE', 'MAHLT',
  'MAHNT', 'MÄHTE', 'MAKEL', 'MALEN', 'MALTE', 'MALVE', 'MANIE', 'MARKE', 'MASKE', 'MASSE',
  'MASTE', 'MATTE', 'MEDIA', 'MEHRE', 'MEIDE', 'MEINE', 'MEINS', 'MEINT', 'MEIST', 'MELDE',
  'MENGE', 'MENÜS', 'MERKE', 'MERKT', 'METRO', 'MIENE', 'MILDE', 'MIMIK', 'MINEN', 'MISST',
  'MIXER', 'MODEM', 'MODUS', 'MÖGEN', 'MOKKA', 'MOLKE', 'MONDE', 'MOORE', 'MOOSE', 'MORAL',
  'MORDE', 'MOTIV', 'MÖWEN', 'MÜDES', 'MÜHEN', 'MULDE', 'MUMIE', 'MUNDE', 'MUSST', 'NACKT',
  'NÄGEL', 'NAGEN', 'NÄHEN', 'NÄHER', 'NÄHRT', 'NAHTE', 'NÄHTE', 'NAIVE', 'NAMEN', 'NARRE',
  'NASEN', 'NASSE', 'NEBEN', 'NEHME', 'NEIDE', 'NEIGE', 'NEIGT', 'NENNE', 'NENNT', 'NEONS',
  'NERVE', 'NERZE', 'NETTE', 'NETZE', 'NEUEN', 'NEUER', 'NICHT', 'NIETE', 'NIMMT', 'NOTAR',
  'NÖTIG', 'NOTIZ', 'NOVUM', 'NUTZE', 'NUTZT', 'OBERE', 'OBHUT', 'OBOEN', 'OFENS', 'ÖFFNE',
  'ÖFTER', 'OHREN', 'OKAPI', 'OKTAV', 'OMEGA', 'OPERN', 'OPTIK', 'ORDEN', 'ORKAN', 'ORTEN',
  'ORTES', 'OZEAN', 'PAARE', 'PACHT', 'PACKT', 'PAGEN', 'PANIK', 'PANNE', 'PAPPE', 'PARKA',
  'PARKE', 'PARKT', 'PARTY', 'PASSE', 'PASST', 'PASTE', 'PATEN', 'PAUKE', 'PECHS', 'PEILT',
  'PELLE', 'PENNE', 'PENNY', 'PESTO', 'PFAND', 'PFIFF', 'PFOTE', 'PHASE', 'PICKT', 'PILLE',
  'PINIE', 'PIRAT', 'PLAGE', 'PLANE', 'PLÄNE', 'PLANT', 'PLUMP', 'PLUTO', 'POKER', 'POLAR',
  'POLEN', 'POLKA', 'PONYS', 'PORTO', 'POSSE', 'PRÄGT', 'PREIS', 'PRISE', 'PROST', 'PRÜFE',
  'PRÜFT', 'PSALM', 'PUDER', 'PULLI', 'PULSE', 'PUMPE', 'PUSTE', 'PUTZE', 'PUTZT', 'QUALM',
  'QUAST', 'QUELL', 'QUERE', 'QUIRL', 'QUITT', 'RABEN', 'RACHE', 'RÄDER', 'RAGEN', 'RAMPE',
  'RANKE', 'RASCH', 'RASUR', 'RATEN', 'RAUBT', 'RÄUME', 'RAUTE', 'REBEN', 'REDEN', 'REDET',
  'REGEL', 'REGIE', 'REIBT', 'REICH', 'REIFE', 'REIHE', 'REINE', 'REIST', 'REITE', 'REIZE',
  'RENNE', 'RENNT', 'RETTE', 'REVUE', 'RIFFE', 'RINGE', 'RINNE', 'RISSE', 'RITTE', 'RITUS',
  'ROBOT', 'ROCKE', 'RODEO', 'ROHRE', 'RÖHRE', 'ROLLE', 'RONDE', 'ROSEN', 'ROSTE', 'ROTEN',
  'ROTOR', 'ROUTE', 'RUBEL', 'RÜBEN', 'RUBIN', 'RÜCKE', 'RUFEN', 'RÜGEN', 'RUHEN', 'RUHIG',
  'RUMPF', 'RUNDE', 'RUNEN', 'RUSSE', 'SÄBEL', 'SACHE', 'SÄFTE', 'SAGEN', 'SÄGEN', 'SAGST',
  'SAGTE', 'SALON', 'SALVE', 'SALZE', 'SAMBA', 'SANDE', 'SANFT', 'SATIN', 'SATTE', 'SÄTZE',
  'SAUCE', 'SAUEN', 'SAUGT', 'SAUNA', 'SAUSE', 'SCHAR', 'SCHON', 'SCHÖN', 'SCHUB', 'SEELE',
  'SEHEN', 'SEIDE', 'SEILE', 'SEKTE', 'SENAT', 'SENDE', 'SENKT', 'SERIE', 'SERUM', 'SESAM',
  'SETZE', 'SETZT', 'SHOWS', 'SIEBE', 'SIEGE', 'SIEGT', 'SILOS', 'SINGE', 'SINGT', 'SINKT',
  'SINNE', 'SITTE', 'SITZE', 'SITZT', 'SKALA', 'SOFAS', 'SOGAR', 'SÖHNE', 'SOMIT', 'SONST',
  'SORGT', 'SORTE', 'SPANN', 'SPARE', 'SPART', 'SPASS', 'SPEER', 'SPORE', 'SPRAY', 'SPRIT',
  'SPUKT', 'SPULE', 'SPÜLT', 'STAAT', 'STÄBE', 'STAMM', 'STAND', 'STARK', 'START', 'STAUT',
  'STEGE', 'STEHT', 'STEIG', 'STEIL', 'STICH', 'STIEG', 'STIER', 'STILL', 'STOCK', 'STOLA',
  'STÖRT', 'STOSS', 'STROH', 'STUCK', 'STUMM', 'STUPS', 'STURZ', 'SUCHE', 'SUCHT', 'SÜDEN',
  'SUITE', 'SUMME', 'SÜNDE', 'SÜSSE', 'TABAK', 'TADEL', 'TAGEN', 'TAGES', 'TAKEL', 'TAKTE',
  'TALAR', 'TALER', 'TANGO', 'TANZE', 'TÄNZE', 'TANZT', 'TAROT', 'TATEN', 'TAUEN', 'TAUFE',
  'TAXIS', 'TEIGE', 'TEILE', 'TEILT', 'TEMPO', 'TENOR', 'TERZE', 'TEUER', 'TEXTE', 'THEKE',
  'THESE', 'TIARA', 'TIERE', 'TILGT', 'TINTE', 'TIPPS', 'TITAN', 'TOBEN', 'TOBTE', 'TOGAS',
  'TOLLE', 'TOPAS', 'TÖPFE', 'TORSO', 'TOTAL', 'TOTEM', 'TOTEN', 'TÖTEN', 'TRAGE', 'TRÄGT',
  'TRAKT', 'TRAMP', 'TRANK', 'TRAUT', 'TREND', 'TRETE', 'TRIAS', 'TRICK', 'TRIEB', 'TRINK',
  'TROLL', 'TROPF', 'TROTZ', 'TRÜBE', 'TRUPP', 'TUBEN', 'TUPFE', 'TURNT', 'TÜTEN', 'TUTUS',
  'TYPEN', 'ÜBELN', 'ÜBERS', 'ÜBRIG', 'ÜBUNG', 'UFERN', 'UFERS', 'UHREN', 'ULMEN', 'UMBAU',
  'UMWEG', 'UMZUG', 'UNART', 'UNFUG', 'UNIKA', 'UNKEN', 'UNTEN', 'UNTER', 'URALT', 'URNEN',
  'VASEN', 'VÄTER', 'VEGAN', 'VENEN', 'VIELE', 'VIREN', 'VISUM', 'VITAL', 'VÖGEL', 'VOLLE',
  'VORAB', 'VORNE', 'VOTUM', 'WABEN', 'WACHE', 'WÄHLE', 'WÄHLT', 'WAHRE', 'WALDE', 'WÄNDE',
  'WANGE', 'WARME', 'WÄRME', 'WARNT', 'WARTE', 'WATTE', 'WEBEN', 'WEGEN', 'WEHEN', 'WEHRT',
  'WEICH', 'WEIDE', 'WEINT', 'WEISE', 'WEISS', 'WEITE', 'WELKT', 'WENIG', 'WERFE', 'WERKE',
  'WERTE', 'WESEN', 'WETTE', 'WICHT', 'WIEGE', 'WILDE', 'WINDE', 'WIRFT', 'WIRKT', 'WIRRE',
  'WIRTE', 'WISCH', 'WITWE', 'WITZE', 'WODKA', 'WOHIN', 'WOHNE', 'WOHNT', 'WÖLFE', 'WORTE',
  'WRACK', 'WÜRDE', 'WÜRFE', 'WÜRZE', 'WÜSTE', 'XENON', 'YETIS', 'ZACKE', 'ZAGEN', 'ZÄHER',
  'ZAHLE', 'ZAHLT', 'ZÄHLT', 'ZANKE', 'ZARTE', 'ZECHE', 'ZEHEN', 'ZEIGE', 'ZEIGT', 'ZELLE',
  'ZELTE', 'ZENIT', 'ZICKE', 'ZIEHE', 'ZIEHT', 'ZIELE', 'ZIERT', 'ZINKE', 'ZINSE', 'ZOBEL',
  'ZÖLLE', 'ZONEN', 'ZÖPFE', 'ZOTTE', 'ZUBER', 'ZUCKT', 'ZÜGEL', 'ZUGES', 'ZUNFT', 'ZUPFT',
  'ZUVOR', 'ZWANG', 'ZWECK', 'ZWEIG', 'ZWIRN', 'ZWÖLF',
];

/* Alles, was eingegeben werden darf: Lösungen plus Zusatzwörter, ohne Dubletten. */
const ALLE_WOERTER = (() => {
  const raus = new Set(LOESUNGEN.map((e) => e[0]));
  for (const w of WEITERE) raus.add(w);
  return [...raus].sort();
})();

const TIPP_ZU = Object.fromEntries(LOESUNGEN);
