/* Wortschatz für Wördle.

   LOESUNGEN  – Wörter, die gezogen werden können. Jedes trägt seinen Tipp:
                eine Umschreibung, in der das Wort selbst nicht vorkommt.
   WEITERE    – zusätzlich erlaubte Rateworte ohne Tipp. Sie tauchen nie
                als Lösung auf, dürfen aber eingegeben werden.

   Alle Wörter in Großbuchstaben, genau fünf Zeichen. Ä, Ö, Ü zählen als
   ein Zeichen und haben eine eigene Taste. ß kommt nicht vor.
*/

const LOESUNGEN = [
  ['APFEL', 'Rundes Obst vom Baum, rot, grün oder gelb – steckt im Strudel und im Mus.'],
  ['BIRNE', 'Obst mit dickem Bauch und schmalem Hals. Hängt auch an der Zimmerdecke und leuchtet.'],
  ['BLUME', 'Wächst im Beet, hat Stiel und Blüte, kommt zum Geburtstag in die Vase.'],
  ['BLUSE', 'Leichtes Oberteil mit Knopfleiste, klassisch für Damen.'],
  ['BODEN', 'Worauf du stehst – oder der staubige Raum ganz oben unterm Dach.'],
  ['BOGEN', 'Krumme Linie. Damit schießt man Pfeile, in der Architektur trägt er das Gewölbe.'],
  ['BRIEF', 'Kommt mit Marke im Umschlag und wird in den Kasten geworfen.'],
  ['BRUST', 'Vorderseite des Oberkörpers, dahinter schlägt das Herz. Auch eine Schwimmart.'],
  ['BUCHE', 'Laubbaum mit glatter grauer Rinde, im Herbst kupferrot. Beliebtes Möbelholz.'],
  ['DAMPF', 'Was aus dem Wasserkocher steigt. Trieb früher die Lokomotiven an.'],
  ['DATUM', 'Tag, Monat, Jahr – steht oben rechts auf jedem Formular.'],
  ['DECKE', 'Liegt beim Fernsehen über den Beinen. Und ist zugleich das Gegenteil vom Fußboden.'],
  ['DIELE', 'Erster Raum hinter der Wohnungstür, wo die Jacken hängen. Auch ein langes Holzbrett.'],
  ['DRAHT', 'Dünner, biegsamer Metallfaden. Man hat ihn auch zu jemandem, mit dem man gut kann.'],
  ['DRECK', 'Was am Schuh klebt, wenn man über den Acker gelaufen ist.'],
  ['EBENE', 'Flaches Land ohne Berge. In der Mathematik eine Fläche ohne Krümmung.'],
  ['EIMER', 'Runder Behälter mit Henkel, für Wasser, Sand oder den Wischmopp.'],
  ['EISEN', 'Graues Metall, das rostet. Beim Golf auch ein Schläger.'],
  ['ENGEL', 'Himmlischer Bote mit Flügeln, sitzt an Weihnachten auf der Baumspitze.'],
  ['ERBSE', 'Kleine grüne Kugel aus der Schote. Eine davon lag unter der Matratze der Prinzessin.'],
  ['ERNTE', 'Was der Bauer im Spätsommer von den Feldern holt.'],
  ['ESSEN', 'Was dreimal am Tag auf den Tisch kommt – und die Tätigkeit dazu.'],
  ['FADEN', 'Dünner Zwirn auf der Rolle, gehört durchs Nadelöhr. Man verliert ihn beim Reden.'],
  ['FAHNE', 'Buntes Tuch an der Stange, wird bei der Siegerehrung gehisst.'],
  ['FALKE', 'Schneller Greifvogel, stürzt sich aus großer Höhe auf die Beute.'],
  ['FARBE', 'Rot, Blau, Grün – und was im Eimer steckt, wenn die Wand gestrichen wird.'],
  ['FASAN', 'Bunter Hühnervogel im Feld, mit sehr langem Schwanz.'],
  ['FEDER', 'Trägt den Vogel. Steckt gespannt im Kugelschreiber und in der Matratze.'],
  ['FEIER', 'Anlass mit Gästen, Kuchen und Musik – Geburtstag, Hochzeit, Jubiläum.'],
  ['FERNE', 'Wo der Horizont ist. Dorthin schweift der Blick, wenn man träumt.'],
  ['FEUER', 'Brennt, knistert und wärmt – aber die Wehr rückt aus, wenn es zu groß wird.'],
  ['FLOTT', 'Zügig und schwungvoll erledigt. Umgangssprachlich auch: sieht schick aus.'],
  ['FLUSS', 'Wasser, das zum Meer strömt. Rhein, Main, Donau.'],
  ['FRAGE', 'Endet mit einem Zeichen wie ein Haken und verlangt eine Antwort.'],
  ['FRIST', 'Zeitraum bis zu einem Stichtag – beim Finanzamt besser nicht verstreichen lassen.'],
  ['FUCHS', 'Rotes Raubtier mit buschiger Rute, gilt im Märchen als besonders schlau.'],
  ['FUNKE', 'Winziger Glutspritzer vom Feuerstein. Auch der zündende Moment einer Idee.'],
  ['GABEL', 'Besteck mit Zinken, liegt links vom Teller. Auch die Stelle, wo sich der Weg teilt.'],
  ['GEBET', 'Gesprochene Zwiesprache mit Gott, oft mit gefalteten Händen.'],
  ['GEIGE', 'Streichinstrument, das unters Kinn geklemmt wird.'],
  ['GEIST', 'Weißes Gespenst im Schloss – und zugleich der Verstand eines Menschen.'],
  ['GLANZ', 'Was frisch poliertes Silber und ein sauberes Auto ausstrahlen.'],
  ['GNADE', 'Milde statt Strafe – der Präsident kann sie einem Verurteilten gewähren.'],
  ['GRUND', 'Warum etwas geschieht. Und das Unterste eines Sees.'],
  ['GURKE', 'Langes grünes Gemüse, sauer eingelegt im Glas, gehört auf jedes Butterbrot.'],
  ['HAFEN', 'Wo die Schiffe anlegen und die Container stehen. Hamburg hat einen großen.'],
  ['HAKEN', 'Gebogenes Metallstück für die Jacke an der Wand. Auch der versteckte Nachteil einer Sache.'],
  ['HALLE', 'Sehr großer überdachter Raum – für Turniere, Messen oder Maschinen.'],
  ['HANDY', 'Kleiner Begleiter in der Hosentasche, mit dem man telefoniert und alles andere macht.'],
  ['HARFE', 'Großes Saiteninstrument zum Zupfen, steht schräg vor dem Spieler.'],
  ['HAUCH', 'Kaum spürbarer Atemzug. Auch: nur ein winziges bisschen von etwas.'],
  ['HAUPT', 'Gehobenes Wort für den Kopf. Als Vorsilbe: das Wichtigste von allem.'],
  ['HEBEL', 'Stange, die Kraft vervielfacht. Archimedes wollte damit die Welt aus den Angeln heben.'],
  ['HECKE', 'Dichte grüne Wand aus Sträuchern an der Grundstücksgrenze, wird geschnitten.'],
  ['HEIDE', 'Karge Landschaft mit lila Blüten, berühmt in der Lüneburger Gegend.'],
  ['HENNE', 'Weibliches Huhn, legt die Eier.'],
  ['HERDE', 'Große Gruppe weidender Tiere, vom Hirten zusammengehalten.'],
  ['HOBEL', 'Werkzeug des Schreiners, zieht Späne vom Brett.'],
  ['HONIG', 'Goldgelbe Süße aus dem Bienenstock, kommt aufs Brot.'],
  ['HUMOR', 'Die Gabe, über die Dinge lachen zu können.'],
  ['HÜTTE', 'Einfaches Häuschen aus Holz, oben am Berg oder hinten im Garten.'],
  ['IMKER', 'Wer Bienen hält und den Honig schleudert.'],
  ['INSEL', 'Land ringsum von Wasser umgeben. Sylt, Rügen, Mallorca.'],
  ['JACKE', 'Was man beim Rausgehen überzieht, mit Reißverschluss oder Knöpfen.'],
  ['JÄGER', 'Geht mit Hund und Gewehr in den Wald, sitzt auf dem Hochsitz.'],
  ['JOKER', 'Karte, die jede andere ersetzen darf. Auch der Trumpf im Ärmel.'],
  ['JUBEL', 'Lauter Freudenschrei der Menge, wenn das Tor fällt.'],
  ['JUNGE', 'Männliches Kind.'],
  ['KABEL', 'Isolierter Strang, der Strom oder Daten leitet – hinterm Schreibtisch immer verknotet.'],
  ['KÄFIG', 'Gitterbehausung für Vogel oder Hamster.'],
  ['KAMEL', 'Wüstentier mit Höckern, kommt lange ohne Wasser aus.'],
  ['KAMIN', 'Offene Feuerstelle im Wohnzimmer, mit Rauchabzug durchs Dach.'],
  ['KANAL', 'Künstlich gegrabener Wasserweg. Auch ein Programmplatz im Fernsehen.'],
  ['KANTE', 'Scharfe Linie, wo zwei Flächen zusammenstoßen – am Tisch schmerzhaft fürs Schienbein.'],
  ['KARTE', 'Zeigt gefaltet den Weg, steckt im Portemonnaie oder wird beim Skat gemischt.'],
  ['KASSE', 'Wo im Laden bezahlt wird – und die Krankenversicherung heißt auch so.'],
  ['KATER', 'Männliche Katze. Und was am Morgen nach zu viel Wein im Kopf hämmert.'],
  ['KATZE', 'Schnurrt auf dem Sofa, fängt Mäuse, hat angeblich neun Leben.'],
  ['KEGEL', 'Spitz zulaufender Körper. Neun davon stehen am Ende der Bahn.'],
  ['KELCH', 'Trinkgefäß mit Fuß, beim Abendmahl in der Kirche.'],
  ['KERZE', 'Wachs mit Docht, spendet Licht beim Stromausfall und im Advent.'],
  ['KETTE', 'Verbundene Glieder aus Metall – am Fahrrad oder um den Hals.'],
  ['KLANG', 'Wie etwas tönt – der volle Ton eines Instruments oder einer Stimme.'],
  ['KLAUE', 'Krallenbewehrter Fuß eines Raubtiers. Auch eine unleserliche Handschrift.'],
  ['KLEID', 'Einteiliges Stück Stoff zum Anziehen, oben und unten in einem, meist für Damen.'],
  ['KLIMA', 'Das Wetter über Jahrzehnte gemittelt – Thema jeder großen Konferenz.'],
  ['KNOPF', 'Kleine runde Scheibe, geht durchs Loch und hält das Hemd zu. Auch zum Drücken.'],
  ['KOHLE', 'Schwarzer Brennstoff aus der Grube. Salopp auch: Geld.'],
  ['KOMET', 'Himmelskörper mit leuchtendem Schweif, kommt alle paar Jahrzehnte vorbei.'],
  ['KÖNIG', 'Trägt Krone und sitzt auf dem Thron. Im Schach die wichtigste Figur.'],
  ['KRAFT', 'Was man zum Heben braucht. In der Physik gemessen in Newton.'],
  ['KRANZ', 'Rund gebundenes Gesteck aus Zweigen – an der Tür oder mit vier Kerzen.'],
  ['KREBS', 'Tier mit Scheren am Meeresgrund. Auch ein Sternzeichen im Juli.'],
  ['KREIS', 'Runde Linie, überall gleich weit vom Mittelpunkt. Auch eine Verwaltungseinheit.'],
  ['KREUZ', 'Zwei Balken übereinander. Steht auf dem Kirchturm, und der Rücken heißt auch so.'],
  ['KRONE', 'Goldreif mit Zacken auf dem Königskopf. Sitzt auch auf dem geschliffenen Zahn.'],
  ['KÜCHE', 'Raum mit Herd, Spüle und Kühlschrank.'],
  ['KUGEL', 'Vollkommen runder Körper – beim Eis, beim Billard, beim Lotto.'],
  ['KUNST', 'Was im Museum hängt und steht. Und was schwer zu machen ist.'],
  ['KURVE', 'Krümmung der Straße. Auch die Linie im Diagramm.'],
  ['KÜSTE', 'Streifen, wo das Land ans Meer stößt.'],
  ['LADEN', 'Geschäft mit Tresen und Ware. Auch das Brett vorm Fenster – und was der Akku braucht.'],
  ['LAMPE', 'Gibt Licht, steht auf dem Nachttisch oder hängt über dem Esstisch.'],
  ['LANZE', 'Lange Stichwaffe des Ritters beim Turnier.'],
  ['LATTE', 'Schmales Brett am Zaun. Beim Fußball das Ding über dem Torwart.'],
  ['LAUNE', 'Gemütszustand – kann gut, schlecht oder wechselhaft sein.'],
  ['LEBEN', 'Was zwischen Geburt und Tod passiert.'],
  ['LEDER', 'Gegerbte Tierhaut für Schuhe, Gürtel und Sofa.'],
  ['LEUTE', 'Mehrere Menschen, ganz allgemein.'],
  ['LICHT', 'Was die Sonne schickt und der Schalter anmacht.'],
  ['LIEBE', 'Das stärkste Gefühl zwischen zwei Menschen.'],
  ['LILIE', 'Große duftende Blüte mit sechs Blättern, oft weiß, häufig im Trauerstrauß.'],
  ['LINDE', 'Herzblättriger Baum, blüht im Sommer, steht traditionell auf dem Dorfplatz.'],
  ['LINIE', 'Gerade zwischen zwei Punkten. Auch der Weg von Bus oder Bahn.'],
  ['LINSE', 'Geschliffenes Glas in Brille und Kamera. Auch die kleine Hülsenfrucht im Eintopf.'],
  ['LUCHS', 'Wildkatze mit Pinselohren, hat sprichwörtlich sehr scharfe Augen.'],
  ['LUNGE', 'Paariges Organ im Brustkorb, nimmt den Sauerstoff auf.'],
  ['MAGEN', 'Hohlorgan unter dem Zwerchfell, in dem das Essen verdaut wird.'],
  ['MÄHNE', 'Langes Haar am Hals von Pferd und Löwe.'],
  ['MALER', 'Streicht die Wände – oder hängt im Museum.'],
  ['MANGO', 'Süße gelborange Tropenfrucht mit großem flachem Kern.'],
  ['MARKT', 'Platz mit Ständen, wo samstags Obst und Gemüse verkauft wird.'],
  ['MAUER', 'Wand aus Stein und Mörtel. Eine berühmte teilte Berlin.'],
  ['MÄUSE', 'Mehrere kleine graue Nager mit langem Schwanz.'],
  ['MEILE', 'Angelsächsisches Längenmaß, gut 1,6 Kilometer.'],
  ['MESSE', 'Große Ausstellung für Fachbesucher. Und der Gottesdienst der Katholiken.'],
  ['METER', 'Grundeinheit der Länge, festgelegt über die Lichtgeschwindigkeit; ein Zollstock misst zwei davon.'],
  ['MIETE', 'Was man dem Eigentümer der Wohnung jeden Monat überweist.'],
  ['MILCH', 'Weißes Getränk von der Kuh, kommt in den Kaffee.'],
  ['MINZE', 'Kühlendes Kraut für Tee und Zahnpasta.'],
  ['MITTE', 'Der Punkt, der von allen Rändern gleich weit weg ist.'],
  ['MÖBEL', 'Tisch, Stuhl, Schrank – alles, was die Wohnung einrichtet.'],
  ['MÖHRE', 'Oranges Wurzelgemüse, das Kaninchen lieben.'],
  ['MONAT', 'Zwölf davon ergeben ein Jahr.'],
  ['MOTOR', 'Wandelt Kraftstoff oder Strom in Bewegung, brummt unter der Haube.'],
  ['MÜHLE', 'Gebäude mit Flügeln oder Wasserrad, das Korn zu Mehl mahlt. Auch ein Brettspiel.'],
  ['MÜNZE', 'Rundes Geldstück aus Metall, klimpert im Portemonnaie.'],
  ['MUSIK', 'Töne in geordneter Folge, kommt aus dem Radio.'],
  ['NABEL', 'Kleine Narbe mitten auf dem Bauch, Rest der Schnur von der Mutter.'],
  ['NACHT', 'Dunkle Zeit zwischen Abend und Morgen.'],
  ['NADEL', 'Spitz und dünn – zum Nähen, am Tannenbaum, oder auf dem Kompass.'],
  ['NAGEL', 'Wird mit dem Hammer in die Wand geschlagen. Sitzt auch vorn auf dem Finger.'],
  ['NARBE', 'Blasser Streifen auf der Haut, der nach einer Verletzung bleibt.'],
  ['NATUR', 'Wald, Wiese, Tiere – alles, was nicht vom Menschen gemacht ist.'],
  ['NEBEL', 'Wolke am Boden, im Herbst sieht man kaum die Hand vor Augen.'],
  ['NEFFE', 'Der Sohn deines Bruders oder deiner Schwester.'],
  ['NIERE', 'Bohnenförmiges Organ, das das Blut filtert. Man hat zwei davon.'],
  ['NUDEL', 'Teigware aus Mehl und Ei, kommt in kochendes Salzwasser.'],
  ['OCHSE', 'Kastriertes männliches Rind, zog früher den Pflug.'],
  ['OFFEN', 'Nicht verschlossen. Auch: ehrlich heraus sagen, was man denkt.'],
  ['OLIVE', 'Kleine grüne oder schwarze Frucht aus dem Süden, liefert Öl.'],
  ['ONKEL', 'Der Bruder von Mutter oder Vater.'],
  ['OPFER', 'Wer den Schaden abbekommen hat. Auch die Gabe an die Götter.'],
  ['ORGEL', 'Riesiges Instrument mit Pfeifen und Pedalen, steht auf der Empore der Kirche.'],
  ['OSTEN', 'Himmelsrichtung, in der die Sonne aufgeht.'],
  ['OTTER', 'Schwimmendes Marder-Tier mit dichtem Fell, knackt Muscheln auf dem Bauch.'],
  ['PAKET', 'Kommt vom Versandhändler, der Bote klingelt damit an der Tür.'],
  ['PALME', 'Baum mit Wedeln statt Ästen, steht am Strand und trägt Kokosnüsse.'],
  ['PANDA', 'Schwarzweißer Bär aus China, frisst fast nur Bambus.'],
  ['PAPST', 'Oberhaupt der katholischen Kirche, wohnt im Vatikan.'],
  ['PAUSE', 'Kurze Unterbrechung – in der Schule mit Brot und Schulhof.'],
  ['PEDAL', 'Wird mit dem Fuß getreten, am Rad, am Klavier oder im Auto.'],
  ['PERLE', 'Schimmernde Kugel aus der Muschel, aufgereiht als Halskette.'],
  ['PFAHL', 'Dicker Holzstab, der in den Boden gerammt wird.'],
  ['PFEIL', 'Fliegt vom Bogen. Zeigt als Zeichen die Richtung an.'],
  ['PFERD', 'Reittier mit Hufen und Mähne, wiehert im Stall.'],
  ['PFLUG', 'Gerät, das die Ackerfurche zieht, hinter dem Traktor.'],
  ['PILOT', 'Sitzt im Cockpit und fliegt das Flugzeug.'],
  ['PISTE', 'Präparierte Abfahrt für Skifahrer. Auch die Startbahn am Flughafen.'],
  ['PLATZ', 'Freie Fläche mitten in der Stadt. Auch der Sitz im Zug – und ein Kommando an den Hund.'],
  ['POKAL', 'Silberner Becher, den der Sieger in die Höhe stemmt.'],
  ['PRIMA', 'Umgangssprachlich: richtig gut, bestens.'],
  ['PRINZ', 'Sohn des Königs, küsst im Märchen die Schlafende wach.'],
  ['PROBE', 'Versuch vor dem Ernstfall – beim Theater und beim Chor. Auch die Menge fürs Labor.'],
  ['PUDEL', 'Hunderasse mit lockigem Fell, wird gern geschoren.'],
  ['PUPPE', 'Spielzeug in Menschengestalt. Auch das Zwischenstadium der Raupe.'],
  ['QUARK', 'Weißer Frischkäse, sauer und cremig, kommt in den Kuchen.'],
  ['QUOTE', 'Anteil in Prozent – beim Fernsehen die Zahl der Zuschauer.'],
  ['RADIO', 'Kasten, aus dem Musik und Nachrichten kommen, empfängt über Antenne.'],
  ['RASEN', 'Kurz gemähte Grasfläche im Garten oder im Stadion.'],
  ['RATTE', 'Großer grauer Nager in der Kanalisation.'],
  ['RAUCH', 'Graue Schwaden über dem Feuer, steigen aus dem Schornstein.'],
  ['RAUPE', 'Gefräßiges Larvenstadium, aus dem später ein Schmetterling wird.'],
  ['RECHT', 'Die Gesamtheit der Gesetze. Und das Gegenteil von falsch.'],
  ['REGAL', 'Möbel aus Brettern, auf denen die Bücher stehen.'],
  ['REGEN', 'Wasser, das aus den Wolken fällt – Schirm aufspannen.'],
  ['REISE', 'Fahrt an einen weit entfernten Ort, mit Koffer.'],
  ['RENTE', 'Monatliches Geld für Menschen, die nicht mehr arbeiten müssen.'],
  ['RIESE', 'Sehr großer Mensch im Märchen, gegen den David antrat.'],
  ['RINDE', 'Äußere Schicht des Baumstamms. Auch die harte Außenseite von Brot und Käse.'],
  ['RIPPE', 'Gebogener Knochen im Brustkorb. Zwölf Paare schützen die Organe.'],
  ['ROBBE', 'Rundlicher Meeressäuger, der sich an den Strand legt und bellt.'],
  ['RUDER', 'Langes Blatt, mit dem man das Boot vorwärts zieht. Auch die Steuerung des Schiffs.'],
  ['RUINE', 'Verfallenes Gemäuer einer alten Burg.'],
  ['SAHNE', 'Fetter Teil der Milch, wird steif geschlagen und kommt auf den Kuchen.'],
  ['SAITE', 'Gespannter Draht auf Gitarre und Geige, erzeugt beim Zupfen den Ton.'],
  ['SALAT', 'Grüne Blätter in der Schüssel, mit Essig und Öl angemacht.'],
  ['SALBE', 'Fettige Creme aus der Tube, wird auf die wunde Haut gestrichen.'],
  ['SAMEN', 'Kleines Korn, aus dem eine neue Pflanze wächst.'],
  ['SÄULE', 'Runde tragende Stütze am griechischen Tempel.'],
  ['SCHAF', 'Wolliges Weidetier, das blökt und geschoren wird.'],
  ['SCHAL', 'Langes Tuch, das man sich im Winter um den Hals wickelt.'],
  ['SCHUH', 'Kommt an den Fuß, hat Sohle und Schnürsenkel.'],
  ['SEGEL', 'Großes Tuch am Mast, das den Wind fängt und das Boot treibt.'],
  ['SEIFE', 'Schäumt beim Händewaschen und macht sauber.'],
  ['SEITE', 'Ein Blatt im Buch, von vorn betrachtet. Auch links oder rechts von etwas.'],
  ['SILBE', 'Sprechteil eines Wortes – Ka-mel hat zwei davon.'],
  ['SIRUP', 'Dickflüssige Zuckerlösung, wird mit Wasser zu Limonade.'],
  ['SOCKE', 'Kommt zwischen Fuß und Schuh, verschwindet gern in der Waschmaschine.'],
  ['SOHLE', 'Unterseite des Fußes und des Schuhs.'],
  ['SONNE', 'Der Stern, um den die Erde kreist, macht Tag und Wärme.'],
  ['SPALT', 'Schmaler Riss, eine nur einen Zentimeter weit geöffnete Tür.'],
  ['SPIEL', 'Was hier gerade läuft – mit Regeln, Runden und einem Ziel.'],
  ['SPORT', 'Körperliche Betätigung mit Schweiß, Verein und Wettkampf.'],
  ['STADT', 'Große Ansammlung von Häusern mit Rathaus und Straßenbahn.'],
  ['STAHL', 'Harte Legierung aus Eisen und Kohlenstoff, wird in der Hütte gekocht.'],
  ['STAUB', 'Feine graue Schicht auf dem Regal, wird gesaugt oder gewischt.'],
  ['STEIN', 'Harter Brocken aus dem Boden. Steckt auch in der Kirsche.'],
  ['STERN', 'Leuchtender Punkt am Nachthimmel. Auch die Auszeichnung des Restaurants.'],
  ['STIEL', 'Langer Griff an Besen und Pfanne. Auch der grüne Halm der Blume.'],
  ['STIRN', 'Glatte Fläche über den Augen, unter dem Haaransatz.'],
  ['STOFF', 'Gewebe für Kleidung. Und was für die Prüfung gelernt werden muss.'],
  ['STROM', 'Kommt aus der Steckdose. Auch ein sehr großer Fluss.'],
  ['STUHL', 'Sitzmöbel mit vier Beinen und Lehne.'],
  ['STURM', 'Sehr starker Wind, der Bäume umwirft.'],
  ['SUPPE', 'Warme Flüssigkeit im tiefen Teller, wird gelöffelt.'],
  ['TAFEL', 'Grüne Wand im Klassenzimmer mit Kreide. Auch die Schokolade.'],
  ['TANNE', 'Immergrüner Nadelbaum, steht an Weihnachten geschmückt im Wohnzimmer.'],
  ['TANTE', 'Die Schwester von Mutter oder Vater.'],
  ['TASSE', 'Gefäß mit Henkel für Kaffee und Tee.'],
  ['TAUBE', 'Grauer Vogel auf dem Marktplatz, gilt als Zeichen des Friedens.'],
  ['TEICH', 'Kleines stehendes Gewässer mit Seerosen und Fröschen.'],
  ['THEMA', 'Worum es in einem Text oder Gespräch geht.'],
  ['THRON', 'Prunkvoller Sessel, auf dem der Herrscher sitzt.'],
  ['TIEFE', 'Wie weit es nach unten geht – beim See in Metern gemessen.'],
  ['TIGER', 'Große gestreifte Raubkatze aus Asien.'],
  ['TISCH', 'Platte auf Beinen, an der gegessen und gearbeitet wird.'],
  ['TITEL', 'Steht vorn auf dem Buch. Auch was der Meister gewinnt und der Doktor führt.'],
  ['TONNE', 'Tausend Kilogramm. Und der große Behälter für den Müll.'],
  ['TORTE', 'Mehrstöckiger Kuchen mit Creme, zum Geburtstag mit Kerzen.'],
  ['TRAUM', 'Bilder im Schlaf. Auch der große Wunsch fürs Leben.'],
  ['TREUE', 'Verlässlich zu jemandem stehen, über Jahre hinweg.'],
  ['TRUHE', 'Große Kiste mit Deckel zum Aufklappen – für Schätze oder Tiefkühlkost.'],
  ['TULPE', 'Frühlingsblume aus der Zwiebel, Wahrzeichen der Niederlande.'],
  ['TÜRME', 'Mehrere hohe schmale Bauwerke, etwa an der Kirche oder im Schach.'],
  ['VATER', 'Männlicher Elternteil.'],
  ['VOGEL', 'Tier mit Federn und Schnabel, das singt und fliegt.'],
  ['WAAGE', 'Zeigt das Gewicht an. Auch ein Sternzeichen im Oktober.'],
  ['WAFFE', 'Gerät zum Kämpfen – Schwert, Gewehr, Kanone.'],
  ['WAGEN', 'Fahrzeug auf Rädern. Und der Mut, etwas Riskantes zu tun.'],
  ['WALZE', 'Schwere Rolle, die den Asphalt platt drückt.'],
  ['WANNE', 'Großes Becken im Bad, in das man sich zum Baden legt.'],
  ['WARZE', 'Kleine harte Wucherung auf der Haut, sitzt gern am Finger.'],
  ['WELLE', 'Rollt aufs Ufer zu. Auch das, worauf das Radio sendet.'],
  ['WENDE', 'Kehrtmachen. Und der Umbruch von 1989 in Deutschland.'],
  ['WERFT', 'Betrieb am Wasser, in dem Schiffe gebaut und repariert werden.'],
  ['WESPE', 'Gelbschwarzes Insekt, das im Spätsommer über den Kuchen herfällt und sticht.'],
  ['WESTE', 'Ärmelloses Oberteil über dem Hemd. Sprichwörtlich sollte sie weiß sein.'],
  ['WIESE', 'Grüne Fläche mit Gras und Blumen, wird gemäht.'],
  ['WOCHE', 'Sieben Tage von Montag bis Sonntag.'],
  ['WOLKE', 'Weiße Ansammlung am Himmel, aus der es regnen kann.'],
  ['WOLLE', 'Weiches Garn vom Schaf, daraus wird der Pullover gestrickt.'],
  ['WUNDE', 'Verletzung der Haut, wird mit Pflaster versorgt.'],
  ['WURST', 'Fleisch in der Pelle – Brat-, Blut- oder Leber-. Und salopp: völlig egal.'],
  ['ZÄHNE', 'Weiße Beißer im Mund, morgens und abends geputzt.'],
  ['ZANGE', 'Werkzeug mit zwei Backen zum Greifen und Kneifen.'],
  ['ZÄUNE', 'Mehrere Begrenzungen aus Latten oder Draht rund ums Grundstück.'],
  ['ZEBRA', 'Gestreiftes Steppenpferd. Sein Name klebt auch am gestreiften Fußgängerübergang.'],
  ['ZEILE', 'Eine waagerechte Reihe Text auf dem Blatt.'],
  ['ZEUGE', 'Wer etwas gesehen hat und vor Gericht darüber aussagt.'],
  ['ZIEGE', 'Meckerndes Tier mit Hörnern und Bart, frisst alles.'],
  ['ZITAT', 'Wörtlich übernommener Satz, kommt in Anführungszeichen.'],
  ['ZUNGE', 'Bewegliches Muskelorgan im Mund, schmeckt und spricht.'],
  ['ZWERG', 'Kleiner Bergarbeiter im Märchen – sieben leben bei Schneewittchen.'],
];

/* Weitere gültige Rateworte – Wörter, die eingegeben werden dürfen, aber nie
   die Lösung sind und darum keinen Tipp brauchen.

   Von Hand zusammengestellt, damit an der App keine fremde Lizenz klebt:
   gängige Hauptwörter im Singular und Plural, gebeugte Zeitwörter, Eigenschafts-
   wörter und die häufigsten kleinen Wörter. Durchgehend groß geschrieben,
   ß steht als SS (GROSS, SPASS), Ä/Ö/Ü zählen als ein Zeichen. */
const WEITERE = [
  'ABART', 'ABBAU', 'ABEND', 'ABGAS', 'ABTEI', 'ABTES', 'ABZUG', 'ACHSE', 'ACHTE', 'ACKER',
  'ÄCKER', 'ADELN', 'ADERN', 'ADLER', 'AFFEN', 'AGENT', 'AHNEN', 'AHNTE', 'AHORN', 'AKTEN',
  'AKTIE', 'AKTIV', 'AKUTE', 'ALARM', 'ALBEN', 'ALGEN', 'ALLEE', 'ALLER', 'ALLES', 'ALPEN',
  'ALTAR', 'ALTEN', 'ALTER', 'ALTES', 'AMPEL', 'AMSEL', 'ÄMTER', 'AMTES', 'ANBAU', 'ANGAB',
  'ANGEL', 'ANGST', 'ANKAM', 'ANKER', 'ANLAG', 'ANRUF', 'ANSAH', 'ANTIK', 'ANZUG', 'ÄPFEL',
  'APRIL', 'ARENA', 'ARGEN', 'ÄRGER', 'ARMEE', 'ÄRMEL', 'ARMEN', 'ARMES', 'ÄRZTE', 'ASCHE',
  'ASSEL', 'ÄSTEN', 'ASTES', 'ATEMS', 'ATLAS', 'ATOME', 'AUGEN', 'AUGUR', 'AUTOR', 'AUTOS',
  'BABYS', 'BÄCHE', 'BACKE', 'BÄCKT', 'BADEN', 'BADET', 'BAHNE', 'BAHRE', 'BALGE', 'BALLE',
  'BÄLLE', 'BANDE', 'BANGE', 'BANGT', 'BÄNKE', 'BANNE', 'BÄREN', 'BARON', 'BARTE', 'BÄRTE',
  'BASIS', 'BATEN', 'BAUCH', 'BAUEN', 'BAUER', 'BÄUME', 'BAUTE', 'BEBEN', 'BEBTE', 'BEERE',
  'BEETE', 'BEIDE', 'BEIGE', 'BEINE', 'BEIZE', 'BEKAM', 'BELAG', 'BELEG', 'BELLE', 'BELLT',
  'BERGE', 'BERGT', 'BERUF', 'BESEN', 'BESTE', 'BETEN', 'BETET', 'BETON', 'BETTE', 'BEUGT',
  'BEULE', 'BEUTE', 'BEVOR', 'BEZUG', 'BIBEL', 'BIBER', 'BIEGE', 'BIEGT', 'BIENE', 'BIEST',
  'BIETE', 'BILDE', 'BINDE', 'BINSE', 'BIRKE', 'BISON', 'BISSE', 'BITTE', 'BLASE', 'BLASS',
  'BLATT', 'BLAUE', 'BLECH', 'BLEIB', 'BLICK', 'BLIEB', 'BLITZ', 'BLOCK', 'BLOND', 'BLÜTE',
  'BOCKE', 'BÖCKE', 'BÖGEN', 'BOHLE', 'BOHNE', 'BOHRT', 'BOMBE', 'BONUS', 'BOOTE', 'BÖRSE',
  'BÖSES', 'BOTEN', 'BOTES', 'BOTIN', 'BOXEN', 'BOXER', 'BRACH', 'BRAND', 'BRATE', 'BRAUE',
  'BRAUN', 'BRAUT', 'BRAVE', 'BREIT', 'BRETT', 'BRISE', 'BROTE', 'BRUCH', 'BRÜHE', 'BUBEN',
  'BUCHS', 'BUCHT', 'BUDEN', 'BÜGEL', 'BUHLE', 'BÜHNE', 'BUNDE', 'BÜNDE', 'BUNTE', 'BÜRDE',
  'BÜRGE', 'BUSCH', 'BUSEN', 'BUSSE', 'CAFES', 'CHAOS', 'CHEFS', 'CHINA', 'CHIPS', 'CHÖRE',
  'CHROM', 'CLOWN', 'CODES', 'COUCH', 'CREME', 'CURRY', 'DACHS', 'DAHER', 'DAMEN', 'DAMIT',
  'DÄMME', 'DÄMON', 'DÄNEN', 'DANKE', 'DANKT', 'DARAN', 'DARIN', 'DARUM', 'DATEI', 'DATEN',
  'DAUER', 'DAVON', 'DECKT', 'DEGEN', 'DEHNE', 'DEHNT', 'DEICH', 'DEINE', 'DEKAN', 'DELLE',
  'DEMUT', 'DENKE', 'DENKT', 'DEPOT', 'DICHT', 'DICKE', 'DIEBE', 'DIEBS', 'DIENE', 'DIENT',
  'DIESE', 'DINGE', 'DINGS', 'DOGGE', 'DOHLE', 'DOLCH', 'DORFE', 'DOSEN', 'DOSIS', 'DRAMA',
  'DRANG', 'DRAUF', 'DREHE', 'DREHT', 'DROGE', 'DROHT', 'DRUCK', 'DUELL', 'DUFTE', 'DÜFTE',
  'DUMME', 'DUMPF', 'DÜNEN', 'DÜNNE', 'DUNST', 'DURCH', 'DURST', 'DUZEN', 'ECHSE', 'ECHTE',
  'ECKEN', 'ECKIG', 'EDLER', 'EDLES', 'EFEUS', 'EGGEN', 'EHREN', 'EHRTE', 'EICHE', 'EIDES',
  'EIFER', 'EIGEN', 'EIGNE', 'EILEN', 'EILIG', 'EILTE', 'EINEM', 'EINEN', 'EINER', 'EINES',
  'EINIG', 'EINST', 'EISES', 'EISIG', 'EITEL', 'EITER', 'EITLE', 'EKELN', 'EKELS', 'EKLIG',
  'ELBEN', 'ELCHE', 'ELEND', 'ELFEN', 'ELFTE', 'ELITE', 'EMAIL', 'ENDEN', 'ENDET', 'ENGEN',
  'ENGES', 'ENKEL', 'ENTEN', 'ERBEN', 'ERDEN', 'ERGAB', 'ERLEN', 'ERNST', 'ERSTE', 'ESELS',
  'ESSIG', 'ETAGE', 'ETHIK', 'ETWAS', 'EULEN', 'EUREN', 'EUROS', 'EUTER', 'EWIGE', 'EXAKT',
  'EXTRA', 'FABEL', 'FÄDEN', 'FÄHIG', 'FAHRT', 'FÄHRT', 'FALLE', 'FALLS', 'FÄLLT', 'FALTE',
  'FANGE', 'FÄNGT', 'FASER', 'FASST', 'FAULE', 'FAULT', 'FAUST', 'FEGEN', 'FEGTE', 'FEHLE',
  'FEHLT', 'FEIGE', 'FEILE', 'FEIND', 'FEINE', 'FELDE', 'FELGE', 'FELLE', 'FERSE', 'FESTE',
  'FETTE', 'FIGUR', 'FILET', 'FILME', 'FINDE', 'FINGE', 'FINTE', 'FIRMA', 'FISCH', 'FIXER',
  'FLACH', 'FLAIR', 'FLECK', 'FLEHT', 'FLIEG', 'FLIRT', 'FLOSS', 'FLÖTE', 'FLUCH', 'FLÜGE',
  'FLUGS', 'FOLGE', 'FOLGT', 'FOLIE', 'FORMT', 'FORST', 'FORUM', 'FOTOS', 'FRAGT', 'FRASS',
  'FRECH', 'FREIE', 'FREMD', 'FREUT', 'FROHE', 'FROST', 'FUGEN', 'FÜGEN', 'FÜHLE', 'FÜHLT',
  'FÜHRT', 'FÜLLE', 'FÜLLT', 'FUNDE', 'FÜRST', 'FÜSSE', 'GABEN', 'GALLE', 'GÄNSE', 'GANZE',
  'GARBE', 'GARDE', 'GARNE', 'GASES', 'GASSE', 'GÄSTE', 'GATTE', 'GEBEN', 'GEBOT', 'GEGEN',
  'GEHEN', 'GEHST', 'GEIER', 'GEIZE', 'GEIZT', 'GELBE', 'GELDE', 'GELEE', 'GELTE', 'GEMÜT',
  'GENAU', 'GENIE', 'GENUG', 'GERÄT', 'GERNE', 'GERTE', 'GESTE', 'GIBST', 'GIFTE', 'GILDE',
  'GIPSE', 'GLATT', 'GLEIS', 'GLIED', 'GLÜCK', 'GNOME', 'GOLDE', 'GÖNNE', 'GRABE', 'GRABT',
  'GRÄBT', 'GRADE', 'GRAMM', 'GRATE', 'GRAUE', 'GREIF', 'GREIS', 'GRIFF', 'GRILL', 'GRIMM',
  'GROBE', 'GROLL', 'GROSS', 'GRUBE', 'GRÜNE', 'GRUSS', 'GUCKT', 'GUNST', 'GURTE', 'GUTEN',
  'GÜTER', 'GUTES', 'HAARE', 'HABEN', 'HAFER', 'HAGEL', 'HAGER', 'HAHNE', 'HÄHNE', 'HALBE',
  'HALLO', 'HALME', 'HALTE', 'HÄLTS', 'HÄNDE', 'HÄNGE', 'HÄNGT', 'HARTE', 'HARZE', 'HASEN',
  'HASST', 'HAUEN', 'HAUER', 'HAUFE', 'HAUSE', 'HAUTE', 'HÄUTE', 'HEBEN', 'HEBER', 'HECHT',
  'HEFTE', 'HEILT', 'HEISS', 'HEIZT', 'HELFE', 'HELLE', 'HELME', 'HEMDE', 'HERBE', 'HERRN',
  'HERZE', 'HEUER', 'HEUTE', 'HEXEN', 'HEXER', 'HILFE', 'HILFT', 'HIRSE', 'HIRTE', 'HITZE',
  'HOCKT', 'HÖFEN', 'HOFFT', 'HOHEN', 'HÖHLE', 'HOLDE', 'HOLEN', 'HOLST', 'HOLZE', 'HÖLZE',
  'HORDE', 'HÖREN', 'HÖRST', 'HOSEN', 'HOTEL', 'HUFEN', 'HÜGEL', 'HÜLLE', 'HUNDE', 'HUPEN',
  'HÜPFT', 'HÜRDE', 'HUSTE', 'IDEEN', 'IDIOT', 'IGELN', 'IGELS', 'IGLUS', 'IHNEN', 'IMMER',
  'IMPFT', 'INDEX', 'INDIZ', 'INNEN', 'INNIG', 'IRREN', 'IRRER', 'IRRTE', 'JAGEN', 'JAHRE',
  'JEANS', 'JEDER', 'JENER', 'JETZT', 'JUCKT', 'JUNGS', 'JUWEL', 'KÄFER', 'KAHLE', 'KAKAO',
  'KÄLTE', 'KAMPF', 'KANNE', 'KAPPE', 'KARGE', 'KARRE', 'KAUEN', 'KAUFE', 'KAUFT', 'KEHLE',
  'KEHRT', 'KEIME', 'KEIMT', 'KELLE', 'KENNE', 'KENNT', 'KERBE', 'KERNE', 'KEULE', 'KIESE',
  'KIOSK', 'KIPPE', 'KIPPT', 'KISTE', 'KLAGE', 'KLAGT', 'KLAMM', 'KLARE', 'KLEBT', 'KLEIN',
  'KLOTZ', 'KLUFT', 'KLUGE', 'KNABE', 'KNAPP', 'KNAST', 'KNIEN', 'KNIET', 'KNOTE', 'KOALA',
  'KOCHE', 'KÖCHE', 'KOCHT', 'KODEX', 'KOMMA', 'KOMMT', 'KÖPFE', 'KOPIE', 'KÖRBE', 'KOSTE',
  'KRACH', 'KRÄHE', 'KRANK', 'KRAUT', 'KRIEG', 'KRIMI', 'KRUME', 'KRUMM', 'KÜHLE', 'KÜHNE',
  'KUNDE', 'KUPPE', 'KURSE', 'KÜRZE', 'KÜSSE', 'KÜSST', 'KUTTE', 'LABOR', 'LACHE', 'LACHS',
  'LACHT', 'LACKE', 'LADET', 'LAGER', 'LAICH', 'LAKEN', 'LANDE', 'LANGE', 'LÄNGE', 'LARVE',
  'LASER', 'LASSE', 'LÄSST', 'LASTE', 'LAUBE', 'LAUCH', 'LÄUFE', 'LÄUFT', 'LAUTE', 'LEBER',
  'LEDIG', 'LEERE', 'LEGEN', 'LEGTE', 'LEHNE', 'LEHRE', 'LEHRT', 'LEIBE', 'LEIDE', 'LEIHT',
  'LEIME', 'LEINE', 'LEISE', 'LENKT', 'LERNE', 'LERNT', 'LESEN', 'LIEBT', 'LIEFE', 'LIEGT',
  'LIEST', 'LIFTE', 'LIGEN', 'LIMIT', 'LINKE', 'LINKS', 'LISTE', 'LITER', 'LOBEN', 'LOCKE',
  'LOGIK', 'LOHNE', 'LÖHNE', 'LOSEN', 'LÖSEN', 'LOSES', 'LOTSE', 'LOTUS', 'LÖWEN', 'LÜCKE',
  'LÜFTE', 'LÜGEN', 'LUPEN', 'LUXUS', 'MACHE', 'MACHT', 'MÄDEL', 'MADEN', 'MAGER', 'MAGIE',
  'MAHLE', 'MAHLT', 'MAHNT', 'MÄHTE', 'MAKEL', 'MALEN', 'MALTE', 'MARKE', 'MASKE', 'MASSE',
  'MASTE', 'MATTE', 'MEHRE', 'MEIDE', 'MEINE', 'MEINS', 'MEINT', 'MEISE', 'MEIST', 'MELDE',
  'MENGE', 'MERKE', 'MERKT', 'MIENE', 'MILDE', 'MIMIK', 'MINEN', 'MISST', 'MODUS', 'MÖGEN',
  'MOLCH', 'MOLKE', 'MONDE', 'MOORE', 'MOOSE', 'MORAL', 'MORDE', 'MOTIV', 'MOTTE', 'MÖWEN',
  'MÜDES', 'MÜHEN', 'MULDE', 'MUNDE', 'MUSST', 'MUTIG', 'MÜTZE', 'NACKT', 'NÄGEL', 'NAGEN',
  'NÄHEN', 'NÄHER', 'NÄHRT', 'NAHTE', 'NÄHTE', 'NAIVE', 'NAMEN', 'NARRE', 'NASEN', 'NASSE',
  'NEBEN', 'NEHME', 'NEIDE', 'NEIGE', 'NEIGT', 'NENNE', 'NENNT', 'NERVE', 'NETTE', 'NETZE',
  'NEUEN', 'NEUER', 'NICHT', 'NIETE', 'NIMMT', 'NOTEN', 'NÖTIG', 'NOTIZ', 'NÜSSE', 'NUTZE',
  'NUTZT', 'OASEN', 'OBERE', 'OBHUT', 'OBOEN', 'OFENS', 'ÖFFNE', 'ÖFTER', 'OHREN', 'OPERN',
  'ORDEN', 'ORKAN', 'ORTEN', 'ORTES', 'OZEAN', 'PAARE', 'PACHT', 'PACKT', 'PANIK', 'PANNE',
  'PAPPE', 'PARKE', 'PARKT', 'PARTY', 'PASSE', 'PASST', 'PASTE', 'PATEN', 'PAUKE', 'PEILT',
  'PELLE', 'PENNE', 'PFAND', 'PFIFF', 'PFOTE', 'PHASE', 'PIANO', 'PICKT', 'PILLE', 'PILZE',
  'PINIE', 'PIZZA', 'PLAGE', 'PLANE', 'PLÄNE', 'PLANT', 'PLUMP', 'POLEN', 'PORTO', 'PRÄGT',
  'PREIS', 'PROSA', 'PROST', 'PRÜFE', 'PRÜFT', 'PSALM', 'PUDER', 'PULLI', 'PULSE', 'PUMPE',
  'PUNKT', 'PUSTE', 'PUTZE', 'PUTZT', 'QUALM', 'QUERE', 'QUIRL', 'QUITT', 'RABEN', 'RACHE',
  'RÄDER', 'RAGEN', 'RANKE', 'RASCH', 'RATEN', 'RAUBT', 'RÄUME', 'REBEN', 'REDEN', 'REDET',
  'REGEL', 'REIBT', 'REICH', 'REIFE', 'REIHE', 'REIME', 'REINE', 'REIST', 'REITE', 'REIZE',
  'RENNE', 'RENNT', 'RETTE', 'REVUE', 'RIFFE', 'RINGE', 'RINNE', 'RISSE', 'RITTE', 'ROCKE',
  'ROHRE', 'RÖHRE', 'ROLLE', 'ROMAN', 'ROSEN', 'ROSTE', 'ROTEN', 'ROTOR', 'ROUTE', 'RUBEL',
  'RÜBEN', 'RÜCKE', 'RUFEN', 'RÜGEN', 'RUHEN', 'RUHIG', 'RUMPF', 'RUNDE', 'RUSSE', 'SÄBEL',
  'SACHE', 'SÄFTE', 'SAGEN', 'SÄGEN', 'SAGST', 'SAGTE', 'SALON', 'SALZE', 'SANDE', 'SANFT',
  'SATTE', 'SÄTZE', 'SAUCE', 'SAUEN', 'SAUER', 'SAUGT', 'SAUSE', 'SCHAR', 'SCHON', 'SCHÖN',
  'SCHUB', 'SEELE', 'SEHEN', 'SEHNE', 'SEIDE', 'SEILE', 'SEKTE', 'SENDE', 'SENKT', 'SERIE',
  'SETZE', 'SETZT', 'SIEBE', 'SIEGE', 'SIEGT', 'SILOS', 'SINGE', 'SINGT', 'SINKT', 'SINNE',
  'SITTE', 'SITZE', 'SITZT', 'SKALA', 'SOFAS', 'SOGAR', 'SÖHNE', 'SOMIT', 'SONST', 'SORGE',
  'SORGT', 'SORTE', 'SPANN', 'SPARE', 'SPART', 'SPASS', 'SPEER', 'SPITZ', 'SPRAY', 'SPUKT',
  'SPULE', 'SPÜLT', 'STAAT', 'STÄBE', 'STAMM', 'STAND', 'STARK', 'START', 'STAUT', 'STEGE',
  'STEHT', 'STEIG', 'STEIL', 'STICH', 'STIEG', 'STIER', 'STILL', 'STOCK', 'STOLZ', 'STÖRT',
  'STOSS', 'STUFE', 'STUMM', 'STURZ', 'SUCHE', 'SUCHT', 'SÜDEN', 'SUMME', 'SUMPF', 'SÜNDE',
  'SÜSSE', 'TABAK', 'TADEL', 'TAGEN', 'TAGES', 'TAKTE', 'TALER', 'TANZE', 'TÄNZE', 'TANZT',
  'TASTE', 'TATEN', 'TAUEN', 'TAUFE', 'TAXIS', 'TEIGE', 'TEILE', 'TEILT', 'TENOR', 'TEUER',
  'TEXTE', 'THEKE', 'TIERE', 'TILGT', 'TINTE', 'TIPPS', 'TITAN', 'TOAST', 'TOBEN', 'TOBTE',
  'TOLLE', 'TÖPFE', 'TOTAL', 'TOTEM', 'TOTEN', 'TÖTEN', 'TRAGE', 'TRÄGT', 'TRANK', 'TRAUT',
  'TREND', 'TRETE', 'TRICK', 'TRIEB', 'TRINK', 'TROLL', 'TROPF', 'TROTZ', 'TRÜBE', 'TRUPP',
  'TUBEN', 'TUPFE', 'TURNT', 'TÜTEN', 'ÜBELN', 'ÜBERS', 'ÜBRIG', 'ÜBUNG', 'UFERN', 'UFERS',
  'UHREN', 'UMBAU', 'UMWEG', 'UMZUG', 'UNART', 'UNFUG', 'UNKEN', 'UNTEN', 'UNTER', 'URALT',
  'URNEN', 'VASEN', 'VÄTER', 'VENEN', 'VERSE', 'VIELE', 'VILLA', 'VIREN', 'VÖGEL', 'VOLLE',
  'VORAB', 'VORNE', 'WACHE', 'WÄHLE', 'WÄHLT', 'WAHRE', 'WALDE', 'WÄNDE', 'WANGE', 'WARME',
  'WÄRME', 'WARNT', 'WARTE', 'WEBEN', 'WEGEN', 'WEHEN', 'WEHRT', 'WEICH', 'WEIDE', 'WEINT',
  'WEISE', 'WEISS', 'WEITE', 'WELKT', 'WENIG', 'WERFE', 'WERKE', 'WERTE', 'WESEN', 'WETTE',
  'WICHT', 'WILDE', 'WINDE', 'WIRFT', 'WIRKT', 'WIRRE', 'WIRTE', 'WISCH', 'WITWE', 'WITZE',
  'WOHIN', 'WOHNE', 'WOHNT', 'WÖLFE', 'WORTE', 'WÜRDE', 'WÜRFE', 'WÜRZE', 'WÜSTE', 'ZACKE',
  'ZAGEN', 'ZÄHER', 'ZAHLE', 'ZAHLT', 'ZÄHLT', 'ZANKE', 'ZARTE', 'ZECHE', 'ZEHEN', 'ZEIGE',
  'ZEIGT', 'ZELLE', 'ZELTE', 'ZENIT', 'ZICKE', 'ZIEHE', 'ZIEHT', 'ZIELE', 'ZIERT', 'ZINKE',
  'ZINSE', 'ZÖLLE', 'ZONEN', 'ZÖPFE', 'ZUCKT', 'ZÜGEL', 'ZUGES', 'ZUNFT', 'ZUPFT', 'ZUVOR',
  'ZWANG', 'ZWECK', 'ZWEIG', 'ZWIRN', 'ZWÖLF',
];

/* Alles, was eingegeben werden darf: Lösungen plus Zusatzwörter, ohne Dubletten. */
const ALLE_WOERTER = (() => {
  const raus = new Set(LOESUNGEN.map((e) => e[0]));
  for (const w of WEITERE) raus.add(w);
  return [...raus].sort();
})();

const TIPP_ZU = Object.fromEntries(LOESUNGEN);
